# Generated by Django 5.1.15 on 2026-07-30 09:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("schedule", "進捗"),
                            ("quality", "品質"),
                            ("risk", "リスク"),
                            ("change", "変更"),
                            ("resource", "稼働"),
                        ],
                        max_length=16,
                        verbose_name="分類",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "情報"),
                            ("warning", "注意"),
                            ("critical", "重大"),
                        ],
                        default="warning",
                        max_length=16,
                        verbose_name="重要度",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "未対応"),
                            ("acknowledged", "確認済み"),
                            ("resolved", "解消"),
                            ("dismissed", "対象外"),
                        ],
                        default="open",
                        max_length=16,
                        verbose_name="状態",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="件名")),
                ("detail", models.TextField(blank=True, verbose_name="詳細")),
                ("detected_at", models.DateTimeField(verbose_name="検知日時")),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="確認日時"
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="ピン留め"),
                ),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="どのデータから検知したか。監査時に AI の主張と根拠を突き合わせる。",
                        verbose_name="根拠",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "アラート",
                "verbose_name_plural": "アラート",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("measured_on", models.DateField(verbose_name="計測日")),
                (
                    "schedule_score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="進捗スコア"
                    ),
                ),
                (
                    "budget_score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="予算スコア"
                    ),
                ),
                (
                    "quality_score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="品質スコア"
                    ),
                ),
                (
                    "resource_score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="稼働スコア"
                    ),
                ),
                (
                    "total_score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="総合スコア"
                    ),
                ),
                (
                    "breakdown",
                    models.JSONField(blank=True, default=dict, verbose_name="算出根拠"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_snapshots",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "ヘルススコア",
                "verbose_name_plural": "ヘルススコア",
                "ordering": ["-measured_on"],
            },
        ),
        migrations.CreateModel(
            name="InterventionProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("title", models.CharField(max_length=300, verbose_name="提案")),
                ("rationale", models.TextField(blank=True, verbose_name="提案理由")),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="提案の裏付け。RAG 引用は chunk_key、実データは対象レコード ID で残す。",
                        verbose_name="根拠",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        help_text="0.0-1.0。AI 未使用のルールベース提案では null。",
                        null=True,
                        verbose_name="信頼度",
                    ),
                ),
                (
                    "recommended_action",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="推奨アクション"
                    ),
                ),
                (
                    "expected_effect",
                    models.TextField(blank=True, verbose_name="期待効果"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "提案中"),
                            ("accepted", "採用"),
                            ("modified", "修正して採用"),
                            ("rejected", "不採用"),
                            ("done", "実施済み"),
                        ],
                        default="proposed",
                        max_length=16,
                        verbose_name="状態",
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="判断日時"
                    ),
                ),
                (
                    "decision_reason",
                    models.TextField(blank=True, verbose_name="判断理由"),
                ),
                (
                    "modified_action",
                    models.TextField(
                        blank=True,
                        help_text="「修正して採用」の場合に、人が書き換えた内容。AI 出力と区別して残す。",
                        verbose_name="修正後のアクション",
                    ),
                ),
                (
                    "agent_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interventions",
                        to="agents.agentrun",
                        verbose_name="生成元の実行",
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interventions",
                        to="dashboard.alert",
                        verbose_name="対応アラート",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intervention_decisions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="判断者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI介入提案",
                "verbose_name_plural": "AI介入提案",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KpiMeasurement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("report_hours", "レポート作業時間"),
                            ("correction_rate", "赤字率（修正率）"),
                            ("fact_error_count", "事実誤認件数"),
                            ("detection_lead_days", "予兆検知の先行日数"),
                        ],
                        max_length=32,
                        verbose_name="指標",
                    ),
                ),
                ("measured_on", models.DateField(verbose_name="計測日")),
                (
                    "baseline_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="基準値",
                    ),
                ),
                (
                    "actual_value",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="実績値"
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="目標値",
                    ),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=32, verbose_name="単位"),
                ),
                ("note", models.TextField(blank=True, verbose_name="備考")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_measurements",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI実績",
                "verbose_name_plural": "KPI実績",
                "ordering": ["-measured_on"],
            },
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["project", "status", "severity"],
                name="dashboard_a_project_f1f8d7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="healthsnapshot",
            constraint=models.UniqueConstraint(
                fields=("project", "measured_on"), name="uniq_health_snapshot_per_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="kpimeasurement",
            constraint=models.UniqueConstraint(
                fields=("project", "kind", "measured_on"), name="uniq_kpi_per_day"
            ),
        ),
    ]
