# Generated by Django 5.1.15 on 2026-07-30 09:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="削除日時"
                    ),
                ),
                ("code", models.SlugField(max_length=64, verbose_name="案件コード")),
                ("name", models.CharField(max_length=200, verbose_name="案件名")),
                ("description", models.TextField(blank=True, verbose_name="概要")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparing", "準備中"),
                            ("on_schedule", "オンスケ案件"),
                            ("attention", "注意案件"),
                            ("delayed", "遅延・課題多発案件"),
                            ("closed", "終了"),
                        ],
                        default="preparing",
                        max_length=32,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "rag_status",
                    models.CharField(
                        choices=[
                            ("green", "Green"),
                            ("yellow", "Yellow"),
                            ("red", "Red"),
                            ("gray", "Gray"),
                        ],
                        default="gray",
                        max_length=16,
                        verbose_name="RAG信号",
                    ),
                ),
                (
                    "progress_percent",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="進捗率"
                    ),
                ),
                (
                    "project_manager",
                    models.CharField(blank=True, max_length=120, verbose_name="PM"),
                ),
                (
                    "pmo_manager",
                    models.CharField(blank=True, max_length=120, verbose_name="PMO"),
                ),
                (
                    "planned_start",
                    models.DateField(blank=True, null=True, verbose_name="計画開始日"),
                ),
                (
                    "planned_end",
                    models.DateField(blank=True, null=True, verbose_name="計画終了日"),
                ),
                (
                    "is_demo",
                    models.BooleanField(
                        default=False,
                        help_text="体験用モック案件。実データと混在させないための区別に使う。",
                        verbose_name="体験用案件",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="accounts.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "案件",
                "verbose_name_plural": "案件",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="マイルストーン名"),
                ),
                ("planned_date", models.DateField(verbose_name="計画日")),
                (
                    "forecast_date",
                    models.DateField(blank=True, null=True, verbose_name="見込日"),
                ),
                (
                    "actual_date",
                    models.DateField(blank=True, null=True, verbose_name="実績日"),
                ),
                (
                    "is_gate",
                    models.BooleanField(default=False, verbose_name="品質ゲート"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "マイルストーン",
                "verbose_name_plural": "マイルストーン",
                "ordering": ["planned_date"],
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("title", models.CharField(max_length=300, verbose_name="課題")),
                ("description", models.TextField(blank=True, verbose_name="内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "未対応"),
                            ("in_progress", "対応中"),
                            ("blocked", "ブロック中"),
                            ("resolved", "解決"),
                            ("closed", "完了"),
                        ],
                        default="open",
                        max_length=32,
                        verbose_name="状態",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("critical", "重大"),
                        ],
                        default="medium",
                        max_length=16,
                        verbose_name="重大度",
                    ),
                ),
                (
                    "owner",
                    models.CharField(blank=True, max_length=120, verbose_name="担当"),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="対応期限"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解決日時"
                    ),
                ),
                (
                    "external_key",
                    models.CharField(
                        blank=True,
                        help_text="Jira 等の課題キー。外部連携は将来対応で、現時点では参照用の文字列として保持する。",
                        max_length=120,
                        verbose_name="外部キー",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "課題",
                "verbose_name_plural": "課題",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Defect",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("title", models.CharField(max_length=300, verbose_name="不具合")),
                ("description", models.TextField(blank=True, verbose_name="内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "新規"),
                            ("analyzing", "分析中"),
                            ("fixing", "修正中"),
                            ("verifying", "確認中"),
                            ("closed", "完了"),
                        ],
                        default="new",
                        max_length=32,
                        verbose_name="状態",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("critical", "重大"),
                        ],
                        default="medium",
                        max_length=16,
                        verbose_name="重大度",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="検出工程"
                    ),
                ),
                (
                    "detected_on",
                    models.DateField(blank=True, null=True, verbose_name="検出日"),
                ),
                (
                    "closed_on",
                    models.DateField(blank=True, null=True, verbose_name="完了日"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "不具合",
                "verbose_name_plural": "不具合",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "role_label",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="案件内の役割"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="利用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "案件メンバー",
                "verbose_name_plural": "案件メンバー",
            },
        ),
        migrations.CreateModel(
            name="QualityMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("measured_on", models.DateField(verbose_name="計測日")),
                (
                    "metric_key",
                    models.CharField(max_length=64, verbose_name="指標キー"),
                ),
                (
                    "metric_label",
                    models.CharField(blank=True, max_length=120, verbose_name="指標名"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="値"
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="目標値",
                    ),
                ),
                (
                    "threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="品質ゲートの合否判定に使う値。",
                        max_digits=12,
                        null=True,
                        verbose_name="閾値",
                    ),
                ),
                (
                    "higher_is_better",
                    models.BooleanField(
                        default=True,
                        help_text="消化率なら True、不具合密度なら False。閾値判定の向きを決める。",
                        verbose_name="値は大きいほど良い",
                    ),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=32, verbose_name="単位"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "品質指標",
                "verbose_name_plural": "品質指標",
                "ordering": ["-measured_on"],
            },
        ),
        migrations.CreateModel(
            name="Risk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("title", models.CharField(max_length=300, verbose_name="リスク")),
                ("description", models.TextField(blank=True, verbose_name="内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("identified", "識別済み"),
                            ("monitoring", "監視中"),
                            ("mitigating", "対応中"),
                            ("materialized", "顕在化"),
                            ("closed", "クローズ"),
                        ],
                        default="identified",
                        max_length=32,
                        verbose_name="状態",
                    ),
                ),
                (
                    "probability",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="発生確率(1-5)"
                    ),
                ),
                (
                    "impact",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="影響度(1-5)"
                    ),
                ),
                ("mitigation", models.TextField(blank=True, verbose_name="対応方針")),
                (
                    "owner",
                    models.CharField(blank=True, max_length=120, verbose_name="担当"),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="対応期限"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "リスク",
                "verbose_name_plural": "リスク",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WbsTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("wbs_code", models.CharField(max_length=64, verbose_name="WBSコード")),
                ("name", models.CharField(max_length=300, verbose_name="タスク名")),
                (
                    "owner",
                    models.CharField(blank=True, max_length=120, verbose_name="担当"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "未着手"),
                            ("in_progress", "進行中"),
                            ("blocked", "ブロック中"),
                            ("done", "完了"),
                            ("archived", "アーカイブ"),
                        ],
                        default="not_started",
                        max_length=32,
                        verbose_name="状態",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("urgent", "最優先"),
                        ],
                        default="medium",
                        max_length=16,
                        verbose_name="優先度",
                    ),
                ),
                (
                    "planned_start",
                    models.DateField(blank=True, null=True, verbose_name="計画開始日"),
                ),
                (
                    "planned_end",
                    models.DateField(blank=True, null=True, verbose_name="計画終了日"),
                ),
                (
                    "actual_start",
                    models.DateField(blank=True, null=True, verbose_name="実績開始日"),
                ),
                (
                    "actual_end",
                    models.DateField(blank=True, null=True, verbose_name="実績終了日"),
                ),
                (
                    "progress_percent",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="進捗率"
                    ),
                ),
                (
                    "is_critical_path",
                    models.BooleanField(default=False, verbose_name="クリティカルパス"),
                ),
                (
                    "next_action",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="次アクション"
                    ),
                ),
                (
                    "ball_holder",
                    models.CharField(
                        blank=True,
                        help_text="次に動く責任者。担当と分けて持つ（顧客待ち・他部署待ちを表現するため）。",
                        max_length=120,
                        verbose_name="ボール保持者",
                    ),
                ),
                (
                    "follow_up_state",
                    models.CharField(
                        choices=[
                            ("none", "フォロー不要"),
                            ("watching", "経過観察"),
                            ("following", "フォロー中"),
                            ("escalated", "エスカレーション済み"),
                        ],
                        default="none",
                        max_length=16,
                        verbose_name="PMOフォロー状態",
                    ),
                ),
                (
                    "evidence_note",
                    models.TextField(
                        blank=True,
                        help_text="この状態・判断の根拠。AI 生成内容を採用した場合もここへ残す。",
                        verbose_name="根拠メモ",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="projects.wbstask",
                        verbose_name="親タスク",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "related_tasks",
                    models.ManyToManyField(
                        blank=True, to="projects.wbstask", verbose_name="関連タスク"
                    ),
                ),
            ],
            options={
                "verbose_name": "WBSタスク",
                "verbose_name_plural": "WBSタスク",
                "ordering": ["wbs_code"],
            },
        ),
        migrations.CreateModel(
            name="ChangeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("title", models.CharField(max_length=300, verbose_name="変更要求")),
                ("description", models.TextField(blank=True, verbose_name="内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "起票"),
                            ("under_review", "影響分析中"),
                            ("pending_approval", "承認待ち"),
                            ("approved", "承認済み"),
                            ("rejected", "却下"),
                        ],
                        default="draft",
                        max_length=32,
                        verbose_name="状態",
                    ),
                ),
                (
                    "requested_by",
                    models.CharField(blank=True, max_length=120, verbose_name="起票者"),
                ),
                (
                    "impact_summary",
                    models.TextField(blank=True, verbose_name="影響分析"),
                ),
                (
                    "impact_scope",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="影響を受ける機能・工程・成果物。関連 WBS は affected_tasks で持つ。",
                        verbose_name="影響範囲",
                    ),
                ),
                (
                    "estimated_effort_days",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="影響工数(人日)",
                    ),
                ),
                (
                    "schedule_impact_days",
                    models.IntegerField(
                        blank=True,
                        help_text="正なら遅延方向。判断材料として影響工数と分けて持つ。",
                        null=True,
                        verbose_name="スケジュール影響(日)",
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="判断日時"
                    ),
                ),
                (
                    "decision_reason",
                    models.TextField(blank=True, verbose_name="判断理由"),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_decisions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="判断者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "affected_tasks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="change_requests",
                        to="projects.wbstask",
                        verbose_name="影響を受けるタスク",
                    ),
                ),
            ],
            options={
                "verbose_name": "変更要求",
                "verbose_name_plural": "変更要求",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uniq_project_code_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["project", "status", "severity"],
                name="projects_is_project_6241d3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="defect",
            index=models.Index(
                fields=["project", "status", "severity"],
                name="projects_de_project_8ed7a3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmember",
            constraint=models.UniqueConstraint(
                fields=("project", "user"), name="uniq_project_member"
            ),
        ),
        migrations.AddConstraint(
            model_name="qualitymetric",
            constraint=models.UniqueConstraint(
                fields=("project", "metric_key", "measured_on"),
                name="uniq_quality_metric_per_day",
            ),
        ),
        migrations.AddIndex(
            model_name="wbstask",
            index=models.Index(
                fields=["project", "status"], name="projects_wb_project_6fc416_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wbstask",
            index=models.Index(
                fields=["project", "priority"], name="projects_wb_project_7a4e25_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="wbstask",
            constraint=models.UniqueConstraint(
                fields=("project", "wbs_code"), name="uniq_wbs_code_per_project"
            ),
        ),
    ]
