# Generated by Django 5.1.15 on 2026-07-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wbstask",
            name="actual_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="人時。EVM の AC の算出に使う",
                max_digits=8,
                null=True,
                verbose_name="実績工数",
            ),
        ),
        migrations.AddField(
            model_name="wbstask",
            name="planned_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="人時。EVM の PV / EV の算出に使う",
                max_digits=8,
                null=True,
                verbose_name="計画工数",
            ),
        ),
    ]
