# Generated by Django 5.1.15 on 2026-07-31 01:43

from django.db import migrations, models


def infer_roles(apps, schema_editor):
    """既存メンバーの案件ロールを、それまでの肩書き文字列から推定する。

    肩書きは自由入力なので完全には決まらない。**迷ったら狭いほうへ倒す**
    （既定は「担当」で、承認権は付かない）。広いほうへ倒すと、
    移行しただけで権限が増えることになる。
    """

    ProjectMember = apps.get_model("projects", "ProjectMember")

    for member in ProjectMember.objects.all().iterator():
        label = (member.role_label or "").strip()

        if "参照" in label or "閲覧" in label:
            role = "viewer"
        elif "PMO" in label.upper():
            role = "pmo"
        elif "責任" in label or "オーナー" in label:
            role = "owner"
        else:
            role = "member"

        if member.role != role:
            member.role = role
            member.save(update_fields=["role"])


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "案件責任者"),
                    ("pmo", "案件PMO"),
                    ("member", "担当"),
                    ("viewer", "参照のみ"),
                ],
                default="member",
                help_text="この案件での権限。テナントロールを広げることはなく、狭めるだけ。",
                max_length=16,
                verbose_name="案件ロール",
            ),
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="role_label",
            field=models.CharField(
                blank=True,
                help_text="表示用の肩書き（「基盤チームリーダー」など）。権限判定には使わない。",
                max_length=64,
                verbose_name="案件内の役割",
            ),
        ),
        migrations.RunPython(infer_roles, migrations.RunPython.noop),
    ]
