# Generated by Django 5.1.15 on 2026-08-11 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("projects", "0002_project_member_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="名称")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("screen", "画面"),
                            ("frontend", "FE"),
                            ("backend", "BE"),
                            ("api", "API"),
                            ("batch", "バッチ"),
                            ("database", "DB"),
                            ("test", "テスト"),
                        ],
                        max_length=32,
                        verbose_name="種別",
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="所有チーム"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "技術要素",
                "verbose_name_plural": "技術要素",
                "ordering": ["project__code", "kind", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "kind", "name"),
                        name="graph_component_unique_name",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="機能名")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "owner",
                    models.CharField(blank=True, max_length=120, verbose_name="責任者"),
                ),
                (
                    "release_target",
                    models.CharField(
                        blank=True,
                        help_text="リリース回・バージョン。マイルストーンとの紐付けは MilestoneTaskLink で持つ。",
                        max_length=120,
                        verbose_name="リリース対象",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "計画中"),
                            ("in_development", "開発中"),
                            ("in_test", "試験中"),
                            ("ready", "リリース準備完了"),
                            ("released", "リリース済み"),
                            ("dropped", "対象外"),
                        ],
                        default="planned",
                        max_length=32,
                        verbose_name="状態",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "機能",
                "verbose_name_plural": "機能",
                "ordering": ["project__code", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "name"), name="graph_feature_unique_name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("depends_on", "依存する"),
                            ("blocks", "ブロックする"),
                            ("impacts", "影響する"),
                            ("implements", "実装する"),
                            ("tests", "検証する"),
                            ("caused_by", "原因である"),
                            ("evidenced_by", "根拠づけられる"),
                            ("discussed_in", "議論されている"),
                            ("forecasts", "予測する"),
                        ],
                        max_length=32,
                        verbose_name="関係型",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("confirmed", "確定"),
                            ("candidate", "候補"),
                            ("rejected", "否定"),
                            ("obsolete", "失効"),
                        ],
                        default="candidate",
                        max_length=16,
                        verbose_name="確認状態",
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("external_id", "外部ID一致"),
                            ("manual", "手動登録"),
                            ("rule", "設定済み規則"),
                            ("signal", "外部Signal"),
                            ("document", "文書"),
                            ("ai_candidate", "AI候補"),
                        ],
                        max_length=32,
                        verbose_name="出所",
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        help_text="外部ID・規則名・Signal識別子など。秘密情報や本文は入れない。",
                        max_length=300,
                        verbose_name="出所の参照",
                    ),
                ),
                ("from_object_id", models.UUIDField()),
                ("to_object_id", models.UUIDField()),
                (
                    "is_cross_project",
                    models.BooleanField(
                        default=False,
                        help_text="明示的に許可された案件間依存だけ True。テナントは必ず一致する。",
                        verbose_name="案件横断",
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        verbose_name="確信度",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="有効開始"
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="有効終了"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="確認日時"
                    ),
                ),
                (
                    "review_reason",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="確認・否定の理由"
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_work_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="確認者",
                    ),
                ),
                (
                    "from_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_links_from",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "to_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_links_to",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "関連",
                "verbose_name_plural": "関連",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "relation_type", "state"],
                        name="graph_workl_project_0ed4b0_idx",
                    ),
                    models.Index(
                        fields=["from_content_type", "from_object_id"],
                        name="graph_workl_from_co_3cf9f2_idx",
                    ),
                    models.Index(
                        fields=["to_content_type", "to_object_id"],
                        name="graph_workl_to_cont_3b65e1_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "relation_type",
                            "from_content_type",
                            "from_object_id",
                            "to_content_type",
                            "to_object_id",
                        ),
                        name="graph_worklink_unique_edge",
                    )
                ],
            },
        ),
    ]
