# Generated by Django 5.1.15 on 2026-08-11 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0001_initial"),
        ("projects", "0002_project_member_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkingCalendar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "working_weekdays",
                    models.CharField(
                        default="0,1,2,3,4",
                        help_text="0=月曜。カンマ区切り。休日・特例日は CalendarDay で上書きする。",
                        max_length=16,
                        verbose_name="勤務曜日",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="標準カレンダー", max_length=120, verbose_name="名称"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "勤務カレンダー",
                "verbose_name_plural": "勤務カレンダー",
            },
        ),
        migrations.CreateModel(
            name="CalendarDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("holiday", "休業日"),
                            ("workday", "臨時稼働日"),
                            ("freeze", "リリース凍結"),
                        ],
                        max_length=16,
                        verbose_name="種別",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=120, verbose_name="名称"),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="graph.workingcalendar",
                        verbose_name="カレンダー",
                    ),
                ),
            ],
            options={
                "verbose_name": "カレンダー特例日",
                "verbose_name_plural": "カレンダー特例日",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="MilestoneTaskLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="False なら着地予測の計算対象にしない。",
                        verbose_name="必須",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="確認日時"
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_milestone_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="確認者",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_links",
                        to="projects.milestone",
                        verbose_name="マイルストーン",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestone_links",
                        to="projects.wbstask",
                        verbose_name="WBSタスク",
                    ),
                ),
            ],
            options={
                "verbose_name": "マイルストーン紐付け",
                "verbose_name_plural": "マイルストーン紐付け",
                "ordering": ["milestone__planned_date", "task__wbs_code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("milestone", "task"), name="graph_milestone_task_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskDependency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "dependency_type",
                    models.CharField(
                        choices=[
                            ("fs", "先行の完了後に開始"),
                            ("ss", "先行の開始後に開始"),
                            ("ff", "先行の完了後に完了"),
                            ("sf", "先行の開始後に完了"),
                        ],
                        default="fs",
                        max_length=4,
                        verbose_name="依存種別",
                    ),
                ),
                (
                    "lag_business_days",
                    models.IntegerField(
                        default=0,
                        help_text="先行の完了から後続の開始まで空ける営業日数。負値は前倒し許容。",
                        verbose_name="ラグ（営業日）",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="確認日時"
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_dependencies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="確認者",
                    ),
                ),
                (
                    "predecessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="successor_links",
                        to="projects.wbstask",
                        verbose_name="先行タスク",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "successor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predecessor_links",
                        to="projects.wbstask",
                        verbose_name="後続タスク",
                    ),
                ),
            ],
            options={
                "verbose_name": "WBS依存",
                "verbose_name_plural": "WBS依存",
                "ordering": ["project__code", "predecessor__wbs_code"],
                "indexes": [
                    models.Index(
                        fields=["project", "predecessor"],
                        name="graph_taskd_project_7de9de_idx",
                    ),
                    models.Index(
                        fields=["project", "successor"],
                        name="graph_taskd_project_c00e10_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("predecessor", "successor"),
                        name="graph_dependency_unique_pair",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("predecessor", models.F("successor")), _negated=True
                        ),
                        name="graph_dependency_no_self_loop",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="workingcalendar",
            constraint=models.UniqueConstraint(
                fields=("project",), name="graph_calendar_one_per_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarday",
            constraint=models.UniqueConstraint(
                fields=("calendar", "date", "kind"), name="graph_calendar_day_unique"
            ),
        ),
    ]
