# Generated by Django 5.1.15 on 2026-07-30 15:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_email_login"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("jira", "Jira"),
                            ("redmine", "Redmine"),
                            ("slack", "Slack"),
                            ("teams", "Microsoft Teams"),
                        ],
                        max_length=32,
                        verbose_name="連携先",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="表示名")),
                ("base_url", models.URLField(blank=True, verbose_name="ベースURL")),
                (
                    "credential_env",
                    models.CharField(
                        blank=True,
                        help_text="例: JIRA_API_TOKEN。値そのものは保存しません",
                        max_length=120,
                        verbose_name="資格情報の環境変数名",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("mock", "モック（APIキー不要）"), ("live", "実API")],
                        default="mock",
                        max_length=16,
                        verbose_name="動作モード",
                    ),
                ),
                (
                    "config",
                    models.JSONField(blank=True, default=dict, verbose_name="接続設定"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最終同期"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="未指定ならテナント全体の接続として扱う",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="accounts.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "外部連携",
                "verbose_name_plural": "外部連携",
                "ordering": ["provider", "name"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(blank=True, max_length=200, verbose_name="宛先"),
                ),
                ("title", models.CharField(max_length=300, verbose_name="件名")),
                ("body", models.TextField(blank=True, verbose_name="本文")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "送信済み"),
                            ("failed", "失敗"),
                            ("skipped", "送信せず"),
                        ],
                        max_length=16,
                        verbose_name="状態",
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="エラー")),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="送信日時"
                    ),
                ),
                (
                    "trigger",
                    models.CharField(blank=True, max_length=64, verbose_name="契機"),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="integrations.connection",
                        verbose_name="接続",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知履歴",
                "verbose_name_plural": "通知履歴",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncedRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(max_length=120, verbose_name="外部ID"),
                ),
                (
                    "external_key",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="外部キー"
                    ),
                ),
                ("external_url", models.URLField(blank=True, verbose_name="外部URL")),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("issue", "課題"),
                            ("task", "WBSタスク"),
                            ("defect", "不具合"),
                        ],
                        max_length=16,
                        verbose_name="内部の種別",
                    ),
                ),
                ("object_id", models.UUIDField(verbose_name="内部ID")),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="内容のハッシュ"
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最終同期"
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="integrations.connection",
                        verbose_name="接続",
                    ),
                ),
            ],
            options={
                "verbose_name": "同期レコード",
                "verbose_name_plural": "同期レコード",
                "ordering": ["-last_synced_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncJob",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("pull", "取込（外部→内部）"),
                            ("push", "送信（内部→外部）"),
                        ],
                        default="pull",
                        max_length=16,
                        verbose_name="方向",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "待機中"),
                            ("running", "実行中"),
                            ("succeeded", "成功"),
                            ("partial", "一部失敗"),
                            ("failed", "失敗"),
                        ],
                        default="queued",
                        max_length=16,
                        verbose_name="状態",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="開始"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="終了"),
                ),
                (
                    "created_count",
                    models.PositiveIntegerField(default=0, verbose_name="新規"),
                ),
                (
                    "updated_count",
                    models.PositiveIntegerField(default=0, verbose_name="更新"),
                ),
                (
                    "skipped_count",
                    models.PositiveIntegerField(default=0, verbose_name="変更なし"),
                ),
                (
                    "failed_count",
                    models.PositiveIntegerField(default=0, verbose_name="失敗"),
                ),
                ("message", models.TextField(blank=True, verbose_name="メッセージ")),
                (
                    "detail",
                    models.JSONField(blank=True, default=dict, verbose_name="詳細"),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="integrations.connection",
                        verbose_name="接続",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="実行者",
                    ),
                ),
            ],
            options={
                "verbose_name": "同期ジョブ",
                "verbose_name_plural": "同期ジョブ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="connection",
            constraint=models.UniqueConstraint(
                fields=("tenant", "provider", "name"), name="unique_connection_name"
            ),
        ),
        migrations.AddIndex(
            model_name="syncedrecord",
            index=models.Index(
                fields=["entity_type", "object_id"],
                name="integration_entity__637d65_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="syncedrecord",
            constraint=models.UniqueConstraint(
                fields=("connection", "external_id"), name="unique_external_record"
            ),
        ),
    ]
