# Generated by Django 5.1.15 on 2026-07-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="provider",
            field=models.CharField(
                choices=[
                    ("jira", "Jira"),
                    ("redmine", "Redmine"),
                    ("slack", "Slack"),
                    ("teams", "Microsoft Teams"),
                    ("confluence", "Confluence"),
                    ("git", "Git (GitHub)"),
                ],
                max_length=32,
                verbose_name="連携先",
            ),
        ),
        migrations.AlterField(
            model_name="syncedrecord",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("issue", "課題"),
                    ("task", "WBSタスク"),
                    ("defect", "不具合"),
                    ("document", "文書"),
                ],
                max_length=16,
                verbose_name="内部の種別",
            ),
        ),
    ]
