# Generated by Django 5.1.15 on 2026-08-12 03:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_email_login"),
        ("agents", "0003_rename_planning_area_label"),
        ("dashboard", "0001_initial"),
        ("integrations", "0002_alter_connection_provider_and_more"),
        ("pmo", "0001_initial"),
        ("projects", "0002_project_member_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PmoWorkItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("detection_triage", "予兆トリアージ"),
                            ("data_quality_repair", "データ品質修復"),
                            ("forecast_review", "予測レビュー"),
                            ("report_cycle", "定例報告サイクル"),
                            ("approval_followup", "承認フォローアップ"),
                            ("integration_recovery", "連携復旧"),
                            ("knowledge_quality", "ナレッジ品質"),
                        ],
                        max_length=32,
                        verbose_name="種別",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("new", "新規"),
                            ("assessing", "評価中"),
                            ("planned", "計画済み"),
                            ("auto_running", "自動実行中"),
                            ("awaiting_confirmation", "確認待ち"),
                            ("awaiting_approval", "承認待ち"),
                            ("executing", "実行中"),
                            ("retry_scheduled", "再試行予約"),
                            ("completed", "完了"),
                            ("cancelled", "取消"),
                            ("hold", "保留"),
                            ("failed", "失敗"),
                        ],
                        default="new",
                        max_length=32,
                        verbose_name="状態",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("urgent", "最優先"),
                        ],
                        default="medium",
                        max_length=16,
                        verbose_name="優先度",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("low", "低"), ("medium", "中"), ("high", "高")],
                        default="medium",
                        max_length=16,
                        verbose_name="リスク",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        help_text="alert / integration_job / forecast / schedule など。",
                        max_length=64,
                        verbose_name="発生源種別",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="発生源キー"
                    ),
                ),
                (
                    "dedupe_key",
                    models.CharField(
                        help_text="source_type + source_key + policy_version から決定的に導く。",
                        max_length=200,
                        verbose_name="重複判定キー",
                    ),
                ),
                (
                    "owner",
                    models.CharField(blank=True, max_length=120, verbose_name="担当"),
                ),
                (
                    "due_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="期限"),
                ),
                (
                    "policy_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="assessing→planned遷移時に評価した policy 結果を固定する。",
                        verbose_name="評価時点のポリシー",
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="相関ID",
                    ),
                ),
                (
                    "block_reason",
                    models.TextField(blank=True, verbose_name="保留・確認待ちの理由"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="dedupe 対象。terminal state（completed/cancelled/hold）到達で False にする。",
                        verbose_name="有効",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pmo_work_items",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pmo_work_items",
                        to="accounts.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "PMO自律作業",
                "verbose_name_plural": "PMO自律作業",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceBundle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "source_type",
                    models.CharField(max_length=64, verbose_name="出所種別"),
                ),
                (
                    "source_ref",
                    models.CharField(
                        help_text="元レコードのURLまたはUUID。表示用文字列を主キーにしない。",
                        max_length=500,
                        verbose_name="出所参照",
                    ),
                ),
                ("captured_at", models.DateTimeField(verbose_name="取得日時")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="失効日時"
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(max_length=128, verbose_name="内容ハッシュ"),
                ),
                (
                    "scope",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="テナント・案件・対象を明示する。",
                        verbose_name="適用範囲",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(blank=True, null=True, verbose_name="信頼度"),
                ),
                (
                    "conflict_group",
                    models.CharField(
                        blank=True,
                        help_text="同じ主張に対する肯定・否定根拠を束ねる。",
                        max_length=200,
                        verbose_name="競合グループ",
                    ),
                ),
                (
                    "agent_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pmo_evidence_bundles",
                        to="agents.agentrun",
                        verbose_name="生成元の実行",
                    ),
                ),
                (
                    "work_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_bundles",
                        to="pmo_automation.pmoworkitem",
                        verbose_name="対象Work Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "根拠バンドル",
                "verbose_name_plural": "根拠バンドル",
                "ordering": ["-captured_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "plan_version",
                    models.PositiveIntegerField(verbose_name="対象plan版"),
                ),
                (
                    "requested_action",
                    models.CharField(max_length=200, verbose_name="要求操作"),
                ),
                (
                    "diff_summary",
                    models.TextField(blank=True, verbose_name="実行前後の差分"),
                ),
                (
                    "required_role",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="必要ロール"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "承認待ち"),
                            ("approved", "承認"),
                            ("rejected", "却下"),
                            ("returned", "差し戻し"),
                            ("expired", "失効"),
                            ("hold", "保留"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状態",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="失効日時"
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="判断日時"
                    ),
                ),
                (
                    "decision_reason",
                    models.TextField(blank=True, verbose_name="判断理由"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="職務分掌チェック用。作成者は自己承認できない。",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="承認者",
                    ),
                ),
                (
                    "last_executed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="職務分掌チェック用。最後の実行者は自己承認できない。",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="最後の実行者",
                    ),
                ),
                (
                    "work_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="pmo_automation.pmoworkitem",
                        verbose_name="対象Work Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "承認依頼",
                "verbose_name_plural": "承認依頼",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "agent_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="agents.agentrun",
                        verbose_name="Agent実行",
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="dashboard.alert",
                        verbose_name="アラート",
                    ),
                ),
                (
                    "approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="pmo_automation.approvalrequest",
                        verbose_name="承認依頼",
                    ),
                ),
                (
                    "deliverable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="pmo.deliverable",
                        verbose_name="成果物",
                    ),
                ),
                (
                    "integration_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="integrations.syncjob",
                        verbose_name="連携ジョブ",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="dashboard.interventionproposal",
                        verbose_name="AI介入提案",
                    ),
                ),
                (
                    "work_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="pmo_automation.pmoworkitem",
                        verbose_name="対象Work Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "関連リンク",
                "verbose_name_plural": "関連リンク",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("version", models.PositiveIntegerField(verbose_name="版")),
                ("summary", models.TextField(blank=True, verbose_name="計画概要")),
                (
                    "automation_level",
                    models.CharField(
                        choices=[
                            ("observe", "観測"),
                            ("internal_apply", "内部反映"),
                            ("confirm", "確認待ち"),
                            ("approve", "承認待ち"),
                            ("prohibited", "禁止"),
                        ],
                        max_length=16,
                        verbose_name="自動化レベル",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("active", "有効"),
                            ("superseded", "失効（新版に置換）"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="状態",
                    ),
                ),
                (
                    "created_from_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pmo_work_plans",
                        to="agents.agentrun",
                        verbose_name="生成元の実行",
                    ),
                ),
                (
                    "work_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="pmo_automation.pmoworkitem",
                        verbose_name="対象Work Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "作業計画",
                "verbose_name_plural": "作業計画",
                "ordering": ["work_item", "-version"],
            },
        ),
        migrations.CreateModel(
            name="WorkStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("order", models.PositiveIntegerField(verbose_name="順序")),
                (
                    "kind",
                    models.CharField(
                        help_text="internal_draft / recalculation / external_notify など。",
                        max_length=64,
                        verbose_name="種別",
                    ),
                ),
                (
                    "automation_level",
                    models.CharField(
                        choices=[
                            ("observe", "観測"),
                            ("internal_apply", "内部反映"),
                            ("confirm", "確認待ち"),
                            ("approve", "承認待ち"),
                            ("prohibited", "禁止"),
                        ],
                        max_length=16,
                        verbose_name="自動化レベル",
                    ),
                ),
                (
                    "input_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="入力スナップショット"
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(max_length=200, verbose_name="冪等性キー"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "未処理"),
                            ("running", "実行中"),
                            ("succeeded", "成功"),
                            ("failed", "失敗"),
                            ("skipped", "スキップ"),
                            ("retry_scheduled", "再試行予約"),
                            ("hold", "保留"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状態",
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(default=0, verbose_name="試行回数"),
                ),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="次回再試行予定"
                    ),
                ),
                (
                    "result_summary",
                    models.TextField(blank=True, verbose_name="結果要約"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="pmo_automation.workplan",
                        verbose_name="所属計画",
                    ),
                ),
            ],
            options={
                "verbose_name": "作業ステップ",
                "verbose_name_plural": "作業ステップ",
                "ordering": ["plan", "order"],
            },
        ),
        migrations.CreateModel(
            name="ExecutionAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("started_at", models.DateTimeField(verbose_name="開始日時")),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="終了日時"
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("succeeded", "成功"),
                            ("failed", "失敗"),
                            ("skipped", "スキップ"),
                        ],
                        max_length=16,
                        verbose_name="結果",
                    ),
                ),
                (
                    "failure_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("credential", "資格情報"),
                            ("permission", "権限"),
                            ("policy", "ポリシー"),
                            ("secrets", "秘密情報"),
                            ("transient", "一時障害"),
                            ("timeout", "タイムアウト"),
                            ("unknown", "不明"),
                            ("test", "テスト"),
                        ],
                        max_length=16,
                        verbose_name="失敗分類",
                    ),
                ),
                ("safe_summary", models.TextField(blank=True, verbose_name="安全要約")),
                (
                    "external_receipt",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="外部ID・結果hash・時刻・connector名のみ。トークンや生本文は入れない。",
                        verbose_name="外部受領証跡",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="pmo_automation.workstep",
                        verbose_name="対象Step",
                    ),
                ),
            ],
            options={
                "verbose_name": "実行試行",
                "verbose_name_plural": "実行試行",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AutomationPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "work_kind",
                    models.CharField(
                        choices=[
                            ("detection_triage", "予兆トリアージ"),
                            ("data_quality_repair", "データ品質修復"),
                            ("forecast_review", "予測レビュー"),
                            ("report_cycle", "定例報告サイクル"),
                            ("approval_followup", "承認フォローアップ"),
                            ("integration_recovery", "連携復旧"),
                            ("knowledge_quality", "ナレッジ品質"),
                        ],
                        max_length=32,
                        verbose_name="対象種別",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("low", "低"), ("medium", "中"), ("high", "高")],
                        max_length=16,
                        verbose_name="対象リスク",
                    ),
                ),
                (
                    "automation_level",
                    models.CharField(
                        choices=[
                            ("observe", "観測"),
                            ("internal_apply", "内部反映"),
                            ("confirm", "確認待ち"),
                            ("approve", "承認待ち"),
                            ("prohibited", "禁止"),
                        ],
                        max_length=16,
                        verbose_name="許可する自動化レベル",
                    ),
                ),
                (
                    "required_role",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="必要ロール"
                    ),
                ),
                (
                    "max_age_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="根拠の最大鮮度(分)"
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1, verbose_name="版")),
                ("enabled", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pmo_automation_policies",
                        to="projects.project",
                        verbose_name="案件（未指定はテナント既定値）",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pmo_automation_policies",
                        to="accounts.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "自動化ポリシー",
                "verbose_name_plural": "自動化ポリシー",
                "ordering": ["tenant", "work_kind", "-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "tenant",
                            "project",
                            "work_kind",
                            "risk_level",
                            "version",
                        ),
                        name="uniq_automation_policy_version",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="pmoworkitem",
            index=models.Index(
                fields=["tenant", "project", "state"],
                name="pmo_automat_tenant__97b43e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pmoworkitem",
            index=models.Index(
                fields=["tenant", "kind", "state"],
                name="pmo_automat_tenant__9c3670_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pmoworkitem",
            index=models.Index(
                fields=["correlation_id"], name="pmo_automat_correla_7739fa_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pmoworkitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("tenant", "dedupe_key"),
                name="uniq_active_pmoworkitem_per_tenant_dedupe",
            ),
        ),
        migrations.AddIndex(
            model_name="evidencebundle",
            index=models.Index(
                fields=["work_item", "conflict_group"],
                name="pmo_automat_work_it_a953fd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["work_item", "status"], name="pmo_automat_work_it_696ad5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="worklink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("alert__isnull", False),
                    ("proposal__isnull", False),
                    ("agent_run__isnull", False),
                    ("deliverable__isnull", False),
                    ("approval__isnull", False),
                    ("integration_job__isnull", False),
                    _connector="OR",
                ),
                name="worklink_at_least_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="workplan",
            constraint=models.UniqueConstraint(
                fields=("work_item", "version"), name="uniq_workplan_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="workstep",
            constraint=models.UniqueConstraint(
                fields=("plan", "order"), name="uniq_workstep_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="workstep",
            constraint=models.UniqueConstraint(
                fields=("plan", "idempotency_key"), name="uniq_workstep_idempotency_key"
            ),
        ),
        migrations.AddIndex(
            model_name="executionattempt",
            index=models.Index(
                fields=["step", "outcome"], name="pmo_automat_step_id_a387df_idx"
            ),
        ),
    ]
