# Generated by Django 5.1.15 on 2026-08-15 09:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_email_login"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantAISetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="外すと入力内容は残したまま、上位の設定（テナント既定・環境変数）に戻る。",
                        verbose_name="この設定を使う",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("openai", "OpenAI API"),
                            ("ollama", "Ollama (ローカル)"),
                            ("local_hash", "ローカルハッシュ（APIキー不要・検証用）"),
                        ],
                        help_text="空なら上位の設定に従う。",
                        max_length=32,
                        verbose_name="AIプロバイダ",
                    ),
                ),
                (
                    "openai_api_key",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="OpenAI APIキー"
                    ),
                ),
                (
                    "openai_org_id",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="OpenAI 組織ID"
                    ),
                ),
                (
                    "openai_project_id",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="OpenAI プロジェクトID"
                    ),
                ),
                (
                    "openai_model",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="OpenAI 回答モデル"
                    ),
                ),
                (
                    "ollama_base_url",
                    models.URLField(
                        blank=True, max_length=300, verbose_name="Ollama URL"
                    ),
                ),
                (
                    "ollama_model",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Ollama 回答モデル"
                    ),
                ),
                (
                    "rag_top_k",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="1回の検索で取得するチャンク数。空なら上位の設定に従う。",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="既定 Top-K",
                    ),
                ),
                (
                    "use_llm_rerank",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="LLMリランク"
                    ),
                ),
                (
                    "use_query_expansion",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="クエリ拡張"
                    ),
                ),
                (
                    "agent_max_loops",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="NFR-AG-002。空なら上位の設定に従う。",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="ループ上限",
                    ),
                ),
                (
                    "agent_timeout_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="NFR-AG-004。空なら上位の設定に従う。",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(600),
                        ],
                        verbose_name="タイムアウト（秒）",
                    ),
                ),
                (
                    "openai_embedding_model",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="OpenAI Embedding"
                    ),
                ),
                (
                    "ollama_embedding_model",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Ollama Embedding"
                    ),
                ),
                (
                    "allow_personal_credentials",
                    models.BooleanField(
                        default=True,
                        help_text="外すとテナント全員がこの既定を使う。個人設定の入力欄は読み取り専用になる。",
                        verbose_name="利用者ごとのAPI設定を許可する",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_setting",
                        to="accounts.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "テナントAI設定",
                "verbose_name_plural": "テナントAI設定",
            },
        ),
        migrations.CreateModel(
            name="UserAISetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="外すと入力内容は残したまま、上位の設定（テナント既定・環境変数）に戻る。",
                        verbose_name="この設定を使う",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("openai", "OpenAI API"),
                            ("ollama", "Ollama (ローカル)"),
                            ("local_hash", "ローカルハッシュ（APIキー不要・検証用）"),
                        ],
                        help_text="空なら上位の設定に従う。",
                        max_length=32,
                        verbose_name="AIプロバイダ",
                    ),
                ),
                (
                    "openai_api_key",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="OpenAI APIキー"
                    ),
                ),
                (
                    "openai_org_id",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="OpenAI 組織ID"
                    ),
                ),
                (
                    "openai_project_id",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="OpenAI プロジェクトID"
                    ),
                ),
                (
                    "openai_model",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="OpenAI 回答モデル"
                    ),
                ),
                (
                    "ollama_base_url",
                    models.URLField(
                        blank=True, max_length=300, verbose_name="Ollama URL"
                    ),
                ),
                (
                    "ollama_model",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Ollama 回答モデル"
                    ),
                ),
                (
                    "rag_top_k",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="1回の検索で取得するチャンク数。空なら上位の設定に従う。",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="既定 Top-K",
                    ),
                ),
                (
                    "use_llm_rerank",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="LLMリランク"
                    ),
                ),
                (
                    "use_query_expansion",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="クエリ拡張"
                    ),
                ),
                (
                    "agent_max_loops",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="NFR-AG-002。空なら上位の設定に従う。",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="ループ上限",
                    ),
                ),
                (
                    "agent_timeout_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="NFR-AG-004。空なら上位の設定に従う。",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(600),
                        ],
                        verbose_name="タイムアウト（秒）",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_setting",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="利用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "利用者AI設定",
                "verbose_name_plural": "利用者AI設定",
            },
        ),
    ]
