# Generated by Django 5.1.15 on 2026-08-29 13:45

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_email_login"),
        ("projects", "0003_projectmember_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("code", models.SlugField(max_length=32, verbose_name="年度コード")),
                ("name", models.CharField(max_length=120, verbose_name="年度名")),
                ("start_on", models.DateField(verbose_name="期首")),
                ("end_on", models.DateField(verbose_name="期末")),
                ("is_current", models.BooleanField(default=False, verbose_name="今期")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_years",
                        to="accounts.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "年度",
                "verbose_name_plural": "年度",
                "ordering": ["-start_on"],
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("org_unit", "組織"),
                            ("member", "メンバー"),
                            ("plan_figure", "計数計画"),
                            ("actual_figure", "計数実績"),
                            ("kpi_target", "KPI目標"),
                            ("kpi_result", "KPI実績"),
                        ],
                        max_length=32,
                        verbose_name="取込種別",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ファイル名"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "取込完了"),
                            ("partial", "一部取込"),
                            ("rejected", "取込なし"),
                        ],
                        max_length=16,
                        verbose_name="結果",
                    ),
                ),
                (
                    "row_count",
                    models.PositiveIntegerField(default=0, verbose_name="データ行数"),
                ),
                (
                    "created_count",
                    models.PositiveIntegerField(default=0, verbose_name="新規"),
                ),
                (
                    "updated_count",
                    models.PositiveIntegerField(default=0, verbose_name="更新"),
                ),
                (
                    "error_count",
                    models.PositiveIntegerField(default=0, verbose_name="エラー"),
                ),
                (
                    "errors",
                    models.JSONField(
                        blank=True, default=list, verbose_name="エラー明細"
                    ),
                ),
                (
                    "context",
                    models.JSONField(blank=True, default=dict, verbose_name="取込条件"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_imports",
                        to="accounts.tenant",
                        verbose_name="テナント",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_imports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="実行者",
                    ),
                ),
            ],
            options={
                "verbose_name": "CSV取込",
                "verbose_name_plural": "CSV取込",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KpiDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("code", models.SlugField(max_length=64, verbose_name="KPIコード")),
                ("name", models.CharField(max_length=200, verbose_name="KPI名")),
                (
                    "unit",
                    models.CharField(blank=True, max_length=32, verbose_name="単位"),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("up_is_good", "高いほど良い"),
                            ("down_is_good", "低いほど良い"),
                        ],
                        default="up_is_good",
                        max_length=16,
                        verbose_name="評価方向",
                    ),
                ),
                (
                    "aggregation",
                    models.CharField(
                        choices=[
                            ("sum", "合計"),
                            ("average", "平均"),
                            ("latest", "最新値"),
                        ],
                        default="sum",
                        help_text="月次実績から年度実績を出す方法。件数は合計、率は平均、残高は最新値。",
                        max_length=16,
                        verbose_name="年度集計方法",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="定義・算出方法"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_definitions",
                        to="accounts.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI",
                "verbose_name_plural": "KPI",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="OrgUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("division", "部"),
                            ("section", "課"),
                            ("project", "プロジェクト"),
                        ],
                        max_length=16,
                        verbose_name="階層",
                    ),
                ),
                ("code", models.SlugField(max_length=64, verbose_name="組織コード")),
                ("name", models.CharField(max_length=200, verbose_name="組織名")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="表示順"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="この組織と配下の計数を編集できる利用者。",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_org_units",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ラインマネージャー",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="performance.orgunit",
                        verbose_name="上位組織",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="PMO 側の案件と対応づける場合に指定する。任意。",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="org_units",
                        to="projects.project",
                        verbose_name="対応する案件",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_units",
                        to="accounts.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "組織",
                "verbose_name_plural": "組織",
                "ordering": ["level", "sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="OrgMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "employee_code",
                    models.CharField(max_length=64, verbose_name="社員番号"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="氏名")),
                (
                    "title",
                    models.CharField(blank=True, max_length=120, verbose_name="役割"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="在籍")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_members",
                        to="accounts.tenant",
                        verbose_name="テナント",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="org_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="利用者",
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="performance.orgunit",
                        verbose_name="所属組織",
                    ),
                ),
            ],
            options={
                "verbose_name": "メンバー",
                "verbose_name_plural": "メンバー",
                "ordering": ["employee_code"],
            },
        ),
        migrations.CreateModel(
            name="KpiResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("month", models.DateField(verbose_name="対象月")),
                (
                    "actual_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="実績値"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("csv", "CSV取込"), ("manual", "手入力")],
                        default="manual",
                        max_length=16,
                        verbose_name="入力経路",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="備考"),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_results",
                        to="performance.fiscalyear",
                        verbose_name="年度",
                    ),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="performance.kpidefinition",
                        verbose_name="KPI",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_results",
                        to="accounts.tenant",
                        verbose_name="テナント",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_results",
                        to="performance.orgmember",
                        verbose_name="メンバー",
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_results",
                        to="performance.orgunit",
                        verbose_name="組織",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI実績",
                "verbose_name_plural": "KPI実績",
                "ordering": ["month", "kpi"],
            },
        ),
        migrations.CreateModel(
            name="ActualFigure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="売上",
                    ),
                ),
                (
                    "gross_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="粗利",
                    ),
                ),
                (
                    "operating_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="利益",
                    ),
                ),
                ("month", models.DateField(verbose_name="対象月")),
                (
                    "source",
                    models.CharField(
                        choices=[("csv", "CSV取込"), ("manual", "手入力")],
                        default="manual",
                        max_length=16,
                        verbose_name="入力経路",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="備考"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actual_figures",
                        to="accounts.tenant",
                        verbose_name="テナント",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_actual_figures",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="最終更新者",
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actual_figures",
                        to="performance.fiscalyear",
                        verbose_name="年度",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actual_figures",
                        to="performance.orgmember",
                        verbose_name="メンバー",
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actual_figures",
                        to="performance.orgunit",
                        verbose_name="組織",
                    ),
                ),
            ],
            options={
                "verbose_name": "実績計数",
                "verbose_name_plural": "実績計数",
                "ordering": ["month", "org_unit"],
            },
        ),
        migrations.CreateModel(
            name="PlanVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("initial", "期初計画"), ("revised", "期中変更計画")],
                        max_length=16,
                        verbose_name="種別",
                    ),
                ),
                (
                    "revision",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="期初計画は 0。期中変更は 1 から順に振る。",
                        verbose_name="改訂番号",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=200, verbose_name="計画名"),
                ),
                ("effective_from", models.DateField(verbose_name="適用開始月")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "作成中"),
                            ("active", "適用中"),
                            ("archived", "取り下げ"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="状態",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="変更理由")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_plan_versions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_versions",
                        to="performance.fiscalyear",
                        verbose_name="年度",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_versions",
                        to="accounts.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "計数計画",
                "verbose_name_plural": "計数計画",
                "ordering": ["fiscal_year", "revision"],
            },
        ),
        migrations.CreateModel(
            name="PlanFigure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="売上",
                    ),
                ),
                (
                    "gross_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="粗利",
                    ),
                ),
                (
                    "operating_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="利益",
                    ),
                ),
                (
                    "month",
                    models.DateField(help_text="月初日で持つ。", verbose_name="対象月"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("csv", "CSV取込"), ("manual", "手入力")],
                        default="manual",
                        max_length=16,
                        verbose_name="入力経路",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="備考"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_figures",
                        to="performance.orgmember",
                        verbose_name="メンバー",
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_figures",
                        to="performance.orgunit",
                        verbose_name="組織",
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="figures",
                        to="performance.planversion",
                        verbose_name="計画版",
                    ),
                ),
            ],
            options={
                "verbose_name": "計画計数",
                "verbose_name_plural": "計画計数",
                "ordering": ["month", "org_unit"],
            },
        ),
        migrations.CreateModel(
            name="KpiTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="目標値"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="備考"),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="performance.kpidefinition",
                        verbose_name="KPI",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_targets",
                        to="performance.orgmember",
                        verbose_name="メンバー",
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_targets",
                        to="performance.orgunit",
                        verbose_name="組織",
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_targets",
                        to="performance.planversion",
                        verbose_name="計画版",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI目標",
                "verbose_name_plural": "KPI目標",
                "ordering": ["kpi", "org_unit"],
            },
        ),
        migrations.AddConstraint(
            model_name="fiscalyear",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uniq_fiscal_year_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="kpidefinition",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uniq_kpi_code_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="orgunit",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uniq_org_unit_code_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="orgmember",
            constraint=models.UniqueConstraint(
                fields=("tenant", "employee_code"),
                name="uniq_org_member_code_per_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="kpiresult",
            index=models.Index(
                fields=["fiscal_year", "month"], name="performance_fiscal__de0f21_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="kpiresult",
            constraint=models.UniqueConstraint(
                condition=models.Q(("member__isnull", True)),
                fields=("kpi", "org_unit", "month"),
                name="uniq_kpi_result_org_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="kpiresult",
            constraint=models.UniqueConstraint(
                condition=models.Q(("member__isnull", False)),
                fields=("kpi", "org_unit", "member", "month"),
                name="uniq_kpi_result_member_month",
            ),
        ),
        migrations.AddIndex(
            model_name="actualfigure",
            index=models.Index(
                fields=["fiscal_year", "month"], name="performance_fiscal__aba205_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="actualfigure",
            constraint=models.UniqueConstraint(
                condition=models.Q(("member__isnull", True)),
                fields=("fiscal_year", "org_unit", "month"),
                name="uniq_actual_figure_org_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="actualfigure",
            constraint=models.UniqueConstraint(
                condition=models.Q(("member__isnull", False)),
                fields=("fiscal_year", "org_unit", "member", "month"),
                name="uniq_actual_figure_member_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="planversion",
            constraint=models.UniqueConstraint(
                fields=("fiscal_year", "kind", "revision"),
                name="uniq_plan_version_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="planversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "initial")),
                fields=("fiscal_year",),
                name="uniq_initial_plan_per_year",
            ),
        ),
        migrations.AddIndex(
            model_name="planfigure",
            index=models.Index(
                fields=["plan_version", "month"], name="performance_plan_ve_97963a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="planfigure",
            constraint=models.UniqueConstraint(
                condition=models.Q(("member__isnull", True)),
                fields=("plan_version", "org_unit", "month"),
                name="uniq_plan_figure_org_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="planfigure",
            constraint=models.UniqueConstraint(
                condition=models.Q(("member__isnull", False)),
                fields=("plan_version", "org_unit", "member", "month"),
                name="uniq_plan_figure_member_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="kpitarget",
            constraint=models.UniqueConstraint(
                condition=models.Q(("member__isnull", True)),
                fields=("kpi", "plan_version", "org_unit"),
                name="uniq_kpi_target_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="kpitarget",
            constraint=models.UniqueConstraint(
                condition=models.Q(("member__isnull", False)),
                fields=("kpi", "plan_version", "org_unit", "member"),
                name="uniq_kpi_target_member",
            ),
        ),
    ]
