# Generated by Django 5.1.15 on 2026-08-11 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("projects", "0002_project_member_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("target_object_id", models.UUIDField()),
                ("as_of", models.DateTimeField(db_index=True, verbose_name="予測時点")),
                (
                    "horizon",
                    models.CharField(
                        choices=[
                            ("2d", "2日後"),
                            ("1w", "1週間後"),
                            ("milestone", "最終期日"),
                        ],
                        max_length=16,
                        verbose_name="地平",
                    ),
                ),
                (
                    "baseline_date",
                    models.DateField(blank=True, null=True, verbose_name="予定日"),
                ),
                (
                    "forecast_date",
                    models.DateField(blank=True, null=True, verbose_name="予測日"),
                ),
                (
                    "variance_business_days",
                    models.IntegerField(
                        blank=True,
                        help_text="正が遅延、負が前倒し。算定不能なら None。",
                        null=True,
                        verbose_name="差分営業日",
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "高"),
                            ("medium", "中"),
                            ("low", "低"),
                            ("unknown", "算定不能"),
                        ],
                        max_length=16,
                        verbose_name="確信度",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        default="deterministic_v1",
                        max_length=32,
                        verbose_name="計算方法",
                    ),
                ),
                (
                    "missing_inputs",
                    models.JSONField(blank=True, default=list, verbose_name="不足入力"),
                ),
                (
                    "summary",
                    models.CharField(blank=True, max_length=300, verbose_name="要約"),
                ),
                (
                    "previous",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="following",
                        to="forecast.forecastsnapshot",
                        verbose_name="前回の予測",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecast_snapshots",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "着地予測",
                "verbose_name_plural": "着地予測",
                "ordering": ["-as_of"],
            },
        ),
        migrations.CreateModel(
            name="ForecastReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("adopt", "採用"),
                            ("correct", "修正して採用"),
                            ("reject", "却下"),
                        ],
                        max_length=16,
                        verbose_name="判断",
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=300, verbose_name="理由"),
                ),
                (
                    "corrected_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="修正後の予測日"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="判断日時"),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forecast_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="forecast.forecastsnapshot",
                    ),
                ),
            ],
            options={
                "verbose_name": "予測レビュー",
                "verbose_name_plural": "予測レビュー",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForecastEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("used", "予測に使用"),
                            ("unused_candidate", "未確認のため不使用"),
                            ("contradicts", "矛盾する情報"),
                        ],
                        default="used",
                        max_length=24,
                        verbose_name="役割",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="補足"),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_links",
                        to="forecast.forecastsnapshot",
                    ),
                ),
            ],
            options={
                "verbose_name": "予測の根拠",
                "verbose_name_plural": "予測の根拠",
            },
        ),
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("slack", "Slack"),
                            ("jira", "Jira"),
                            ("redmine", "Redmine"),
                            ("git", "Git"),
                            ("ci", "CI"),
                            ("test_management", "テスト管理"),
                            ("confluence", "Confluence"),
                            ("manual", "手動登録"),
                            ("internal", "本システム"),
                        ],
                        max_length=32,
                        verbose_name="情報源",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="外部イベントID・課題キー・メッセージID。冪等化の第一の鍵。",
                        max_length=200,
                        verbose_name="外部ID",
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("defect_reported", "不具合の起票"),
                            ("defect_updated", "不具合の更新"),
                            ("issue_updated", "課題の更新"),
                            ("test_failed", "テスト失敗"),
                            ("test_passed", "テスト成功"),
                            ("build_result", "ビルド結果"),
                            ("commit", "コミット・PR"),
                            ("schedule_update", "日程の更新"),
                            ("conversation", "会話"),
                            ("other", "その他"),
                        ],
                        max_length=32,
                        verbose_name="分類",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(db_index=True, verbose_name="発生時刻"),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="取得時刻"
                    ),
                ),
                (
                    "permalink",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="原文リンク"
                    ),
                ),
                ("summary", models.CharField(max_length=300, verbose_name="要約")),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="最大 1000 文字。全文は保存しない。",
                        verbose_name="抜粋",
                    ),
                ),
                (
                    "author_reference",
                    models.CharField(
                        blank=True,
                        help_text="表示名またはIDの参照。メールアドレス・個人情報は入れない。",
                        max_length=120,
                        verbose_name="発信者の参照",
                    ),
                ),
                (
                    "channel_reference",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="チャンネル・プロジェクトの参照",
                    ),
                ),
                (
                    "visibility_scope",
                    models.CharField(
                        choices=[
                            ("project", "案件メンバー"),
                            ("tenant", "テナント内"),
                            ("restricted", "限定（登録者と管理者のみ）"),
                        ],
                        default="project",
                        max_length=16,
                        verbose_name="可視範囲",
                    ),
                ),
                (
                    "payload_hash",
                    models.CharField(
                        help_text="外部IDが無い情報源の冪等化に使う。",
                        max_length=64,
                        verbose_name="内容ハッシュ",
                    ),
                ),
                (
                    "is_revoked",
                    models.BooleanField(
                        default=False,
                        help_text="外部で削除・権限変更された場合に立てる。物理削除せず根拠の有効性を落とす。",
                        verbose_name="無効",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="forecast.signal",
                        verbose_name="訂正後のSignal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signal",
                "verbose_name_plural": "Signal",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.AddField(
            model_name="forecastsnapshot",
            name="evidence",
            field=models.ManyToManyField(
                related_name="forecasts",
                through="forecast.ForecastEvidence",
                to="forecast.signal",
                verbose_name="根拠",
            ),
        ),
        migrations.AddField(
            model_name="forecastevidence",
            name="signal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence_links",
                to="forecast.signal",
            ),
        ),
        migrations.AddIndex(
            model_name="signal",
            index=models.Index(
                fields=["project", "source", "occurred_at"],
                name="forecast_si_project_64b913_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="signal",
            index=models.Index(
                fields=["project", "classification"],
                name="forecast_si_project_5714ae_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="signal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("source", "external_id"),
                name="forecast_signal_unique_external_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="signal",
            constraint=models.UniqueConstraint(
                fields=("project", "source", "payload_hash"),
                name="forecast_signal_unique_payload",
            ),
        ),
        migrations.AddIndex(
            model_name="forecastsnapshot",
            index=models.Index(
                fields=["project", "horizon", "-as_of"],
                name="forecast_fo_project_85829b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="forecastsnapshot",
            index=models.Index(
                fields=["target_content_type", "target_object_id"],
                name="forecast_fo_target__cfab6d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastsnapshot",
            constraint=models.UniqueConstraint(
                fields=("target_content_type", "target_object_id", "horizon", "as_of"),
                name="forecast_snapshot_unique_point",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("confidence", "unknown"), ("forecast_date__isnull", True)
                    ),
                    models.Q(("confidence", "unknown"), _negated=True),
                    _connector="OR",
                ),
                name="forecast_snapshot_unknown_has_no_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastevidence",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "signal"), name="forecast_evidence_unique"
            ),
        ),
    ]
