# Generated by Django 5.1.15 on 2026-08-11 13:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("forecast", "0001_initial"),
        ("projects", "0002_project_member_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResolutionEstimate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("target_object_id", models.UUIDField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("fix", "修正完了"),
                            ("retest", "再試験完了"),
                            ("task_finish", "タスク完了"),
                        ],
                        max_length=16,
                        verbose_name="種別",
                    ),
                ),
                ("expected_date", models.DateField(verbose_name="見込み日")),
                (
                    "confirmed_at",
                    models.DateTimeField(db_index=True, verbose_name="確認日時"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="補足"),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        help_text="未確認の見込みは登録できない。予測はここにある日付だけを使う。",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolution_estimates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="確認者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolution_estimates",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "解消見込み",
                "verbose_name_plural": "解消見込み",
                "ordering": ["-confirmed_at"],
                "indexes": [
                    models.Index(
                        fields=[
                            "target_content_type",
                            "target_object_id",
                            "-confirmed_at",
                        ],
                        name="forecast_re_target__c616ad_idx",
                    )
                ],
            },
        ),
    ]
