# Generated by Django 5.1.15 on 2026-08-11 13:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0002_resolutionestimate"),
        ("projects", "0002_project_member_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="InboundEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("source", models.CharField(max_length=32, verbose_name="情報源")),
                (
                    "external_event_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="外部イベントID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=64, verbose_name="イベント種別"),
                ),
                (
                    "payload_hash",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="内容ハッシュ"
                    ),
                ),
                ("occurred_at", models.DateTimeField(verbose_name="発生時刻")),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="受付時刻"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "受付"),
                            ("processed", "処理済み"),
                            ("duplicate", "重複"),
                            ("failed", "失敗"),
                            ("ignored", "対象外"),
                        ],
                        default="received",
                        max_length=16,
                        verbose_name="状態",
                    ),
                ),
                (
                    "error_reason",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="失敗理由"
                    ),
                ),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="forecast.inboundevent",
                        verbose_name="重複元",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "signal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inbound_events",
                        to="forecast.signal",
                        verbose_name="正規化後のSignal",
                    ),
                ),
            ],
            options={
                "verbose_name": "受信イベント",
                "verbose_name_plural": "受信イベント",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "source", "-received_at"],
                        name="forecast_in_project_6c29df_idx",
                    ),
                    models.Index(
                        fields=["status"], name="forecast_in_status_2f724d_idx"
                    ),
                ],
            },
        ),
    ]
