# Generated by Django 5.1.15 on 2026-08-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0003_inboundevent"),
        ("projects", "0002_project_member_role"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="signal",
            name="forecast_signal_unique_external_id",
        ),
        migrations.AddConstraint(
            model_name="signal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("project", "source", "external_id"),
                name="forecast_signal_unique_external_id",
            ),
        ),
    ]
