# Generated by Django 5.1.15 on 2026-08-11 13:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0004_remove_signal_forecast_signal_unique_external_id_and_more"),
        ("graph", "0002_workingcalendar_calendarday_milestonetasklink_and_more"),
        ("projects", "0002_project_member_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "external_id",
                    models.CharField(max_length=200, verbose_name="外部ID"),
                ),
                ("name", models.CharField(max_length=300, verbose_name="テスト名")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("unit", "単体"),
                            ("integration", "結合"),
                            ("system", "システム"),
                            ("uat", "受入"),
                            ("regression", "回帰"),
                        ],
                        max_length=16,
                        verbose_name="種別",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("passed", "成功"),
                            ("failed", "失敗"),
                            ("blocked", "実施不可"),
                            ("skipped", "未実施"),
                        ],
                        max_length=16,
                        verbose_name="結果",
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(db_index=True, verbose_name="実施時刻"),
                ),
                (
                    "environment",
                    models.CharField(blank=True, max_length=120, verbose_name="環境"),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="失敗理由"
                    ),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, max_length=500, verbose_name="外部URL"),
                ),
                (
                    "retest_planned_on",
                    models.DateField(
                        blank=True,
                        help_text="未登録なら、QA工程の完了時期を推定しない（算定不能の理由になる）。",
                        null=True,
                        verbose_name="再試験予定日",
                    ),
                ),
                (
                    "defect_reference",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="関連不具合の外部キー"
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("csv", "CSV取込"),
                            ("manual", "手動登録"),
                            ("connector", "テスト管理ツール"),
                        ],
                        default="csv",
                        max_length=16,
                        verbose_name="入力元",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_evidence",
                        to="graph.feature",
                        verbose_name="対象機能",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "テスト証跡",
                "verbose_name_plural": "テスト証跡",
                "ordering": ["-executed_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "result", "-executed_at"],
                        name="forecast_te_project_4a8361_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "external_id"),
                        name="forecast_test_evidence_unique",
                    )
                ],
            },
        ),
    ]
