# Generated by Django 5.1.15 on 2026-07-30 09:55

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="削除日時"
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="文書名")),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.documents.models.document_upload_path,
                        verbose_name="ファイル",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("xlsx", "Excel (.xlsx)"),
                            ("xlsm", "Excel (.xlsm)"),
                            ("xls", "Excel (.xls)"),
                            ("docx", "Word (.docx)"),
                            ("doc", "Word (.doc)"),
                            ("pptx", "PowerPoint (.pptx)"),
                        ],
                        max_length=16,
                        verbose_name="種別",
                    ),
                ),
                ("file_size", models.BigIntegerField(default=0, verbose_name="サイズ")),
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="ハッシュ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "RAG対象"),
                            ("excluded", "RAG対象外"),
                            ("missing", "ファイル未検出"),
                            ("error", "変換・登録エラー"),
                        ],
                        default="active",
                        max_length=16,
                        verbose_name="状態",
                    ),
                ),
                (
                    "source_note",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="出典メモ"
                    ),
                ),
                (
                    "last_indexed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最終インデックス日時"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="未設定ならテナント共通ナレッジ。",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="accounts.tenant",
                        verbose_name="テナント",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="登録者",
                    ),
                ),
            ],
            options={
                "verbose_name": "文書",
                "verbose_name_plural": "文書",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "page_number",
                    models.PositiveIntegerField(
                        default=1, verbose_name="ページ/シート番号"
                    ),
                ),
                (
                    "section_label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="シート名・見出し"
                    ),
                ),
                ("content", models.TextField(verbose_name="本文")),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="documents.document",
                        verbose_name="文書",
                    ),
                ),
            ],
            options={
                "verbose_name": "文書ページ",
                "verbose_name_plural": "文書ページ",
                "ordering": ["document", "page_number"],
            },
        ),
        migrations.CreateModel(
            name="IngestJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("convert", "本文変換"),
                            ("index", "インデックス構築"),
                            ("reindex", "再インデックス"),
                        ],
                        max_length=16,
                        verbose_name="種別",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "待機中"),
                            ("running", "実行中"),
                            ("succeeded", "成功"),
                            ("failed", "失敗"),
                        ],
                        default="queued",
                        max_length=16,
                        verbose_name="状態",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="開始日時"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="終了日時"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="メッセージ")),
                (
                    "stats",
                    models.JSONField(blank=True, default=dict, verbose_name="統計"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingest_jobs",
                        to="documents.document",
                        verbose_name="文書",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingest_jobs",
                        to="accounts.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "取込ジョブ",
                "verbose_name_plural": "取込ジョブ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="削除日時"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="ひな型名")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "file",
                    models.FileField(
                        upload_to="templates/", verbose_name="ひな型ファイル"
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="検索キーワード"
                    ),
                ),
                (
                    "sheet_outline",
                    models.JSONField(
                        blank=True, default=list, verbose_name="シート構成"
                    ),
                ),
                (
                    "field_mapping",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="回答項目 → セル位置の対応。AI 提案後、人が確認して承認する。",
                        verbose_name="項目マッピング",
                    ),
                ),
                (
                    "mapping_status",
                    models.CharField(
                        choices=[
                            ("unconfigured", "未設定"),
                            ("draft", "下書き"),
                            ("approved", "承認済み"),
                            ("needs_review", "要確認"),
                        ],
                        default="unconfigured",
                        max_length=16,
                        verbose_name="マッピング状態",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="accounts.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "ひな型",
                "verbose_name_plural": "ひな型",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TemplateOutput",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="template_outputs/", verbose_name="出力ファイル"
                    ),
                ),
                (
                    "warnings",
                    models.JSONField(blank=True, default=list, verbose_name="警告"),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="template_outputs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="生成者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="template_outputs",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "ひな型出力",
                "verbose_name_plural": "ひな型出力",
                "ordering": ["-created_at"],
            },
        ),
    ]
