# Generated by Django 5.1.15 on 2026-07-30 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("rag", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="templateoutput",
            name="source_answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="template_outputs",
                to="rag.raganswer",
                verbose_name="元になった回答",
            ),
        ),
        migrations.AddField(
            model_name="templateoutput",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outputs",
                to="documents.template",
                verbose_name="ひな型",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["tenant", "status"], name="documents_d_tenant__1461e3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentpage",
            constraint=models.UniqueConstraint(
                fields=("document", "page_number", "section_label"),
                name="uniq_document_page",
            ),
        ),
    ]
