# Generated by Django 5.1.15 on 2026-07-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("xlsx", "Excel (.xlsx)"),
                    ("xlsm", "Excel (.xlsm)"),
                    ("xls", "Excel (.xls)"),
                    ("docx", "Word (.docx)"),
                    ("doc", "Word (.doc)"),
                    ("pptx", "PowerPoint (.pptx)"),
                    ("txt", "テキスト (.txt)"),
                    ("md", "Markdown (.md)"),
                ],
                max_length=16,
                verbose_name="種別",
            ),
        ),
    ]
