# Generated by Django 5.1.15 on 2026-07-30 09:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("documents", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RagAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("body", models.TextField(verbose_name="回答本文")),
                ("summary", models.TextField(blank=True, verbose_name="判断サマリ")),
                (
                    "grounded_findings",
                    models.TextField(
                        blank=True, verbose_name="登録情報から確認できること"
                    ),
                ),
                (
                    "general_guidance",
                    models.TextField(blank=True, verbose_name="一般情報による補足"),
                ),
                (
                    "unverified_points",
                    models.TextField(
                        blank=True, verbose_name="資料上は確認できないこと"
                    ),
                ),
                (
                    "recommended_actions",
                    models.JSONField(
                        blank=True, default=list, verbose_name="推奨アクション"
                    ),
                ),
                (
                    "follow_up_questions",
                    models.JSONField(
                        blank=True, default=list, verbose_name="追加確認事項"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="生成プロバイダ"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="生成モデル"
                    ),
                ),
                (
                    "knowledge_balance",
                    models.PositiveSmallIntegerField(
                        default=70,
                        help_text="0 に近いほど一般知識寄り、100 に近いほど登録文書寄り。",
                        verbose_name="RAG/一般情報バランス",
                    ),
                ),
            ],
            options={
                "verbose_name": "RAG回答",
                "verbose_name_plural": "RAG回答",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="タイトル"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="アーカイブ"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_sessions",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to="accounts.tenant",
                        verbose_name="テナント",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="利用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "チャットセッション",
                "verbose_name_plural": "チャットセッション",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "chunk_key",
                    models.CharField(
                        db_index=True,
                        help_text="文書・ページ・位置から決まる安定 ID。再構築しても同じ値になる。",
                        max_length=64,
                        verbose_name="チャンクキー",
                    ),
                ),
                (
                    "page_number",
                    models.PositiveIntegerField(default=1, verbose_name="ページ"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="文書内の順序"),
                ),
                ("text", models.TextField(verbose_name="本文")),
                (
                    "token_count",
                    models.PositiveIntegerField(default=0, verbose_name="トークン数"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="メタデータ"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="documents.document",
                        verbose_name="文書",
                    ),
                ),
            ],
            options={
                "verbose_name": "チャンク",
                "verbose_name_plural": "チャンク",
                "ordering": ["document", "position"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "利用者"),
                            ("assistant", "AI"),
                            ("system", "システム"),
                        ],
                        max_length=16,
                        verbose_name="発言者",
                    ),
                ),
                ("content", models.TextField(verbose_name="本文")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="rag.chatsession",
                        verbose_name="セッション",
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_messages",
                        to="rag.raganswer",
                        verbose_name="対応する回答",
                    ),
                ),
            ],
            options={
                "verbose_name": "チャットメッセージ",
                "verbose_name_plural": "チャットメッセージ",
                "ordering": ["session", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnswerCitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("claim", models.TextField(blank=True, verbose_name="対応する主張")),
                ("quoted_text", models.TextField(blank=True, verbose_name="引用")),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="rag.chunk",
                        verbose_name="根拠チャンク",
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="rag.raganswer",
                        verbose_name="回答",
                    ),
                ),
            ],
            options={
                "verbose_name": "根拠",
                "verbose_name_plural": "根拠",
            },
        ),
        migrations.CreateModel(
            name="RetrievalQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("question", models.TextField(verbose_name="質問")),
                (
                    "expanded_queries",
                    models.JSONField(
                        blank=True, default=list, verbose_name="拡張クエリ"
                    ),
                ),
                (
                    "top_k",
                    models.PositiveSmallIntegerField(
                        default=8, verbose_name="取得件数"
                    ),
                ),
                (
                    "used_vector",
                    models.BooleanField(default=True, verbose_name="ベクトル検索"),
                ),
                (
                    "used_lexical",
                    models.BooleanField(default=True, verbose_name="語彙検索"),
                ),
                (
                    "used_rerank",
                    models.BooleanField(default=False, verbose_name="LLMリランク"),
                ),
                (
                    "elapsed_ms",
                    models.PositiveIntegerField(default=0, verbose_name="所要時間(ms)"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retrieval_queries",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retrieval_queries",
                        to="accounts.tenant",
                        verbose_name="テナント",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retrieval_queries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="実行者",
                    ),
                ),
            ],
            options={
                "verbose_name": "検索実行",
                "verbose_name_plural": "検索実行",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="raganswer",
            name="query",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answer",
                to="rag.retrievalquery",
                verbose_name="検索実行",
            ),
        ),
        migrations.CreateModel(
            name="VectorIndex",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("tenant", "テナント共通"), ("project", "案件別")],
                        default="tenant",
                        max_length=16,
                        verbose_name="範囲",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "未構築"),
                            ("building", "構築中"),
                            ("ready", "構築済み"),
                            ("error", "要確認"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状態",
                    ),
                ),
                (
                    "embedding_provider",
                    models.CharField(
                        default="local_hash",
                        max_length=32,
                        verbose_name="Embeddingプロバイダ",
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        default="local-hash-v1",
                        max_length=120,
                        verbose_name="Embeddingモデル",
                    ),
                ),
                (
                    "dimension",
                    models.PositiveIntegerField(default=0, verbose_name="次元数"),
                ),
                (
                    "chunk_count",
                    models.PositiveIntegerField(default=0, verbose_name="チャンク数"),
                ),
                (
                    "built_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="構築日時"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector_indexes",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector_indexes",
                        to="accounts.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "検索インデックス",
                "verbose_name_plural": "検索インデックス",
            },
        ),
        migrations.AddField(
            model_name="chunk",
            name="index",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="rag.vectorindex",
                verbose_name="インデックス",
            ),
        ),
        migrations.CreateModel(
            name="RetrievedChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("rank", models.PositiveSmallIntegerField(verbose_name="順位")),
                (
                    "vector_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="ベクトルスコア"
                    ),
                ),
                (
                    "lexical_score",
                    models.FloatField(blank=True, null=True, verbose_name="語彙スコア"),
                ),
                (
                    "rerank_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="リランクスコア"
                    ),
                ),
                (
                    "final_score",
                    models.FloatField(default=0.0, verbose_name="最終スコア"),
                ),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retrievals",
                        to="rag.chunk",
                        verbose_name="チャンク",
                    ),
                ),
                (
                    "query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="rag.retrievalquery",
                        verbose_name="検索実行",
                    ),
                ),
            ],
            options={
                "verbose_name": "検索結果",
                "verbose_name_plural": "検索結果",
                "ordering": ["query", "rank"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("query", "rank"), name="uniq_rank_per_query"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="vectorindex",
            constraint=models.UniqueConstraint(
                fields=("tenant", "project"), name="uniq_vector_index_per_scope"
            ),
        ),
        migrations.AddConstraint(
            model_name="chunk",
            constraint=models.UniqueConstraint(
                fields=("index", "chunk_key"), name="uniq_chunk_key_per_index"
            ),
        ),
    ]
