# Generated by Django 5.1.15 on 2026-07-30 22:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_email_login"),
        ("documents", "0003_alter_document_file_type"),
        ("projects", "0001_initial"),
        ("rag", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "suite",
                    models.CharField(
                        choices=[
                            ("retrieval", "検索評価（ベクトル+語彙）"),
                            ("retrieval_offline", "APIなし検索評価（語彙のみ）"),
                            ("answer", "回答評価 dry-run"),
                            ("static", "静的チェック"),
                        ],
                        max_length=32,
                        verbose_name="スイート",
                    ),
                ),
                (
                    "top_k",
                    models.PositiveSmallIntegerField(
                        default=8, verbose_name="評価対象の上位件数"
                    ),
                ),
                (
                    "case_count",
                    models.PositiveIntegerField(default=0, verbose_name="評価件数"),
                ),
                (
                    "evaluable",
                    models.BooleanField(default=False, verbose_name="評価可能"),
                ),
                (
                    "unavailable_reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="評価不能の理由"
                    ),
                ),
                (
                    "recall_at_k",
                    models.FloatField(blank=True, null=True, verbose_name="Recall@K"),
                ),
                (
                    "precision_at_k",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Precision@K"
                    ),
                ),
                ("mrr", models.FloatField(blank=True, null=True, verbose_name="MRR")),
                (
                    "pass_rate",
                    models.FloatField(blank=True, null=True, verbose_name="合格率"),
                ),
                (
                    "issues",
                    models.JSONField(blank=True, default=list, verbose_name="検出事項"),
                ),
                (
                    "metrics",
                    models.JSONField(blank=True, default=dict, verbose_name="補助指標"),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluation_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="実行者",
                    ),
                ),
                (
                    "index",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluation_runs",
                        to="rag.vectorindex",
                        verbose_name="対象インデックス",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluation_runs",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_runs",
                        to="accounts.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "評価実行",
                "verbose_name_plural": "評価実行",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoldenQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("question", models.TextField(verbose_name="質問")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="カテゴリ"
                    ),
                ),
                (
                    "expected_document_titles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="登録時点の文書名。参照が消えたことを検知するために保持する。",
                        verbose_name="期待文書名スナップショット",
                    ),
                ),
                (
                    "expected_terms",
                    models.JSONField(
                        blank=True, default=list, verbose_name="期待キーワード"
                    ),
                ),
                (
                    "required_sections",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="回答評価 dry-run で本文に含まれることを確認する見出し。",
                        verbose_name="回答に必須のセクション",
                    ),
                ),
                (
                    "must_abstain",
                    models.BooleanField(
                        default=False,
                        help_text="登録文書に無いはずの質問。断定せず確認を促すことを期待する。",
                        verbose_name="根拠不足なら回答を抑制すべき",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                ("note", models.TextField(blank=True, verbose_name="備考")),
                (
                    "expected_documents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="golden_questions",
                        to="documents.document",
                        verbose_name="期待する文書",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="golden_questions",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="golden_questions",
                        to="accounts.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "Golden質問",
                "verbose_name_plural": "Golden質問",
                "ordering": ["category", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="表示順"),
                ),
                ("question", models.TextField(verbose_name="質問")),
                (
                    "evaluable",
                    models.BooleanField(default=True, verbose_name="評価可能"),
                ),
                ("passed", models.BooleanField(default=False, verbose_name="合格")),
                (
                    "first_hit_rank",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="初出順位"
                    ),
                ),
                (
                    "recall",
                    models.FloatField(blank=True, null=True, verbose_name="Recall"),
                ),
                (
                    "precision",
                    models.FloatField(blank=True, null=True, verbose_name="Precision"),
                ),
                (
                    "reciprocal_rank",
                    models.FloatField(blank=True, null=True, verbose_name="逆順位"),
                ),
                (
                    "matched_documents",
                    models.JSONField(
                        blank=True, default=list, verbose_name="命中した期待文書"
                    ),
                ),
                (
                    "missing_documents",
                    models.JSONField(
                        blank=True, default=list, verbose_name="出なかった期待文書"
                    ),
                ),
                (
                    "issues",
                    models.JSONField(blank=True, default=list, verbose_name="検出事項"),
                ),
                (
                    "detail",
                    models.JSONField(blank=True, default=dict, verbose_name="詳細"),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="rag.evaluationrun",
                        verbose_name="評価実行",
                    ),
                ),
                (
                    "golden",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases",
                        to="rag.goldenquestion",
                        verbose_name="Golden質問",
                    ),
                ),
            ],
            options={
                "verbose_name": "評価ケース",
                "verbose_name_plural": "評価ケース",
                "ordering": ["run", "position"],
            },
        ),
        migrations.AddIndex(
            model_name="evaluationrun",
            index=models.Index(
                fields=["tenant", "suite", "-created_at"],
                name="rag_evaluat_tenant__28bed8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="goldenquestion",
            index=models.Index(
                fields=["tenant", "is_active"], name="rag_goldenq_tenant__766fa8_idx"
            ),
        ),
    ]
