# Generated by Django 5.1.15 on 2026-07-30 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_alter_document_file_type"),
        ("projects", "0001_initial"),
        ("rag", "0002_evaluationrun_goldenquestion_evaluationcase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chunk",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="案件別に検索範囲を切るための境界。テナント共通の文書は null。",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rag_chunks",
                to="projects.project",
                verbose_name="案件",
            ),
        ),
        migrations.AddField(
            model_name="chunk",
            name="source_id",
            field=models.UUIDField(
                blank=True, db_index=True, null=True, verbose_name="出典レコードID"
            ),
        ),
        migrations.AddField(
            model_name="chunk",
            name="source_label",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="出典表示名"
            ),
        ),
        migrations.AddField(
            model_name="chunk",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("document", "文書"),
                    ("issue", "課題"),
                    ("defect", "不具合"),
                    ("risk", "リスク"),
                    ("change_request", "変更要求"),
                    ("wbs_task", "WBSタスク"),
                ],
                db_index=True,
                default="document",
                max_length=32,
                verbose_name="出典種別",
            ),
        ),
        migrations.AddField(
            model_name="chunk",
            name="source_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="差分インデックスの判定に使う。元レコードの updated_at を写す。",
                null=True,
                verbose_name="出典の更新日時",
            ),
        ),
        migrations.AlterField(
            model_name="chunk",
            name="document",
            field=models.ForeignKey(
                blank=True,
                help_text="業務データ由来のチャンクは文書に紐づかないため null になる。",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="documents.document",
                verbose_name="文書",
            ),
        ),
    ]
