# Generated by Django 5.1.15 on 2026-08-12 05:40

import datetime
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_email_login"),
        ("projects", "0002_project_member_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="イベントID",
                    ),
                ),
                ("correlation_id", models.UUIDField(verbose_name="相関ID")),
                (
                    "previous_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="直前のevent_hash"
                    ),
                ),
                (
                    "event_hash",
                    models.CharField(max_length=64, verbose_name="このイベントのhash"),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="実行主体")),
                (
                    "event_type",
                    models.CharField(max_length=64, verbose_name="イベント種別"),
                ),
                ("result", models.CharField(max_length=32, verbose_name="結果")),
                (
                    "detail",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="秘密値・認証情報・生本文は入れない。安全な要約のみ。",
                        verbose_name="詳細",
                    ),
                ),
            ],
            options={
                "verbose_name": "監査イベント",
                "verbose_name_plural": "監査イベント",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["correlation_id"], name="pmo_authori_correla_193e8a_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExecutionCapability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "capability_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="capability ID",
                    ),
                ),
                ("work_item_id", models.UUIDField(verbose_name="対象Work Item ID")),
                (
                    "plan_version",
                    models.PositiveIntegerField(verbose_name="対象plan版"),
                ),
                (
                    "policy_bundle_sha256",
                    models.CharField(
                        max_length=64, verbose_name="policy bundleハッシュ"
                    ),
                ),
                (
                    "requested_action",
                    models.CharField(max_length=200, verbose_name="要求操作"),
                ),
                (
                    "resource_id",
                    models.CharField(max_length=200, verbose_name="対象リソースID"),
                ),
                (
                    "payload_sha256",
                    models.CharField(max_length=64, verbose_name="実行内容ハッシュ"),
                ),
                (
                    "evidence_bundle_sha256",
                    models.CharField(
                        max_length=64, verbose_name="根拠バンドルハッシュ"
                    ),
                ),
                (
                    "approved_by_subject_id",
                    models.CharField(max_length=200, verbose_name="承認者subject_id"),
                ),
                (
                    "required_role",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="必要ロール"
                    ),
                ),
                ("issued_at", models.DateTimeField(verbose_name="発行日時")),
                ("expires_at", models.DateTimeField(verbose_name="失効日時")),
                (
                    "nonce",
                    models.CharField(max_length=64, unique=True, verbose_name="nonce"),
                ),
                (
                    "idempotency_key",
                    models.CharField(max_length=200, verbose_name="冪等性キー"),
                ),
                (
                    "signature",
                    models.TextField(verbose_name="署名（HMAC-SHA256, hex）"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "発行済み"),
                            ("consumed", "実行済み"),
                            ("expired", "失効"),
                            ("revoked", "取消"),
                        ],
                        default="issued",
                        max_length=16,
                        verbose_name="状態",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "実行capability",
                "verbose_name_plural": "実行capability",
                "ordering": ["-issued_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status"],
                        name="pmo_authori_tenant__b24ff9_idx",
                    ),
                    models.Index(
                        fields=["work_item_id"], name="pmo_authori_work_it_648597_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "expires_at__lte",
                                django.db.models.expressions.CombinedExpression(
                                    models.F("issued_at"),
                                    "+",
                                    models.Value(datetime.timedelta(seconds=600)),
                                ),
                            )
                        ),
                        name="execution_capability_ttl_max_600s",
                    )
                ],
            },
        ),
    ]
