# Generated by Django 5.1.15 on 2026-08-12 06:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_email_login"),
        ("pmo_authority", "0001_initial"),
        ("projects", "0002_project_member_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="KillSwitch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "全体"),
                            ("tenant", "テナント"),
                            ("project", "案件"),
                            ("connector", "コネクタ"),
                            ("operation", "操作"),
                        ],
                        max_length=16,
                        verbose_name="範囲",
                    ),
                ),
                (
                    "connector",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="コネクタ"
                    ),
                ),
                (
                    "operation",
                    models.CharField(blank=True, max_length=64, verbose_name="操作"),
                ),
                (
                    "is_tripped",
                    models.BooleanField(default=True, verbose_name="作動中（停止中）"),
                ),
                ("reason", models.TextField(blank=True, verbose_name="理由")),
                (
                    "activated_by",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="作動させた主体"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "kill switch",
                "verbose_name_plural": "kill switch",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["scope", "is_tripped"],
                        name="pmo_authori_scope_9199a5_idx",
                    ),
                    models.Index(
                        fields=["tenant", "is_tripped"],
                        name="pmo_authori_tenant__8a4f49_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("connector", ""),
                                ("operation", ""),
                                ("project__isnull", True),
                                ("scope", "global"),
                                ("tenant__isnull", True),
                            ),
                            models.Q(
                                ("connector", ""),
                                ("operation", ""),
                                ("project__isnull", True),
                                ("scope", "tenant"),
                                ("tenant__isnull", False),
                            ),
                            models.Q(
                                ("connector", ""),
                                ("operation", ""),
                                ("project__isnull", False),
                                ("scope", "project"),
                                ("tenant__isnull", True),
                            ),
                            models.Q(
                                ("connector__gt", ""),
                                ("operation", ""),
                                ("project__isnull", True),
                                ("scope", "connector"),
                                ("tenant__isnull", True),
                            ),
                            models.Q(
                                ("connector", ""),
                                ("operation__gt", ""),
                                ("project__isnull", True),
                                ("scope", "operation"),
                                ("tenant__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="kill_switch_scope_fields_match",
                    )
                ],
            },
        ),
    ]
