# Generated by Django 5.1.15 on 2026-08-12 06:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pmo_authority", "0002_killswitch"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyBundle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "commit_sha",
                    models.CharField(max_length=64, verbose_name="コミットSHA"),
                ),
                (
                    "content_sha256",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="bundle内容のハッシュ"
                    ),
                ),
                (
                    "signature",
                    models.TextField(verbose_name="署名（HMAC-SHA256, hex）"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
            ],
            options={
                "verbose_name": "policy bundle",
                "verbose_name_plural": "policy bundle",
                "ordering": ["-created_at"],
            },
        ),
    ]
