# Generated by Django 5.1.15 on 2026-07-30 09:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("agents", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deliverable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("weekly_report", "週次報告"),
                            ("monthly_report", "月次報告"),
                            ("quality_report", "品質レポート"),
                            ("incident_summary", "障害サマリー"),
                            ("meeting_minutes", "議事録"),
                            ("other", "その他"),
                        ],
                        default="other",
                        max_length=32,
                        verbose_name="種別",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="タイトル")),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="差し戻し後に作り直すたびに繰り上げる。承認済みの版は本文を変更しない。",
                        verbose_name="版",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("pending_approval", "承認待ち"),
                            ("approved", "承認済み"),
                            ("rejected", "差し戻し"),
                        ],
                        default="draft",
                        max_length=32,
                        verbose_name="状態",
                    ),
                ),
                (
                    "ai_generated_body",
                    models.TextField(blank=True, verbose_name="AI生成本文"),
                ),
                ("body", models.TextField(blank=True, verbose_name="確定本文")),
                (
                    "agent_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliverables",
                        to="agents.agentrun",
                        verbose_name="生成元の実行",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliverables",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverables",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "成果物",
                "verbose_name_plural": "成果物",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("requested", "承認依頼"),
                            ("approved", "承認"),
                            ("rejected", "差し戻し"),
                        ],
                        max_length=16,
                        verbose_name="判断",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="コメント")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="実施者",
                    ),
                ),
                (
                    "deliverable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="pmo.deliverable",
                        verbose_name="成果物",
                    ),
                ),
            ],
            options={
                "verbose_name": "承認履歴",
                "verbose_name_plural": "承認履歴",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="計画名")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("reviewing", "レビュー中"),
                            ("finalized", "確定"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="状態",
                    ),
                ),
                ("body", models.TextField(blank=True, verbose_name="計画本文")),
                (
                    "review_points",
                    models.JSONField(
                        blank=True, default=list, verbose_name="レビュー観点"
                    ),
                ),
                (
                    "agent_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_drafts",
                        to="agents.agentrun",
                        verbose_name="生成元の実行",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_drafts",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "計画ドラフト",
                "verbose_name_plural": "計画ドラフト",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="削除日時"
                    ),
                ),
                ("key", models.SlugField(max_length=64, verbose_name="キー")),
                ("title", models.CharField(max_length=200, verbose_name="名称")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="カテゴリ"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("body", models.TextField(verbose_name="プロンプト本文")),
                (
                    "intent",
                    models.CharField(
                        blank=True,
                        help_text="apps.agents.models.Intent の値。空なら汎用。",
                        max_length=32,
                        verbose_name="対応する意図",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_templates",
                        to="accounts.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "プロンプトテンプレート",
                "verbose_name_plural": "プロンプトテンプレート",
                "ordering": ["category", "title"],
            },
        ),
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("question", models.TextField(verbose_name="相談内容")),
                (
                    "agent_run",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultation",
                        to="agents.agentrun",
                        verbose_name="Agentic実行",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultations",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="accounts.tenant",
                        verbose_name="テナント",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="相談者",
                    ),
                ),
                (
                    "prompt_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultations",
                        to="pmo.prompttemplate",
                        verbose_name="使用テンプレート",
                    ),
                ),
            ],
            options={
                "verbose_name": "PMO相談",
                "verbose_name_plural": "PMO相談",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="prompttemplate",
            constraint=models.UniqueConstraint(
                fields=("tenant", "key"), name="uniq_prompt_key_per_tenant"
            ),
        ),
    ]
