# Generated by Django 5.1.15 on 2026-08-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pmo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approval",
            name="decision",
            field=models.CharField(
                choices=[
                    ("requested", "承認依頼"),
                    ("approved", "承認"),
                    ("rejected", "差し戻し"),
                    ("withdrawn", "取り下げ"),
                ],
                max_length=16,
                verbose_name="判断",
            ),
        ),
    ]
