# Generated by Django 5.1.15 on 2026-07-30 09:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("rag_search", "RAG検索"),
                            ("rag_chat", "RAGチャット"),
                            ("pmo_consultation", "PMO相談"),
                            ("planning", "計画策定"),
                            ("deliverable", "成果物生成"),
                        ],
                        max_length=32,
                        verbose_name="実行画面",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "実行中"),
                            ("succeeded", "完了"),
                            ("failed", "失敗"),
                            ("aborted", "中断"),
                        ],
                        default="running",
                        max_length=16,
                        verbose_name="状態",
                    ),
                ),
                ("user_input", models.TextField(verbose_name="入力")),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("delay", "進捗遅延"),
                            ("risk", "リスク相談"),
                            ("issue", "課題整理"),
                            ("quality", "品質懸念"),
                            ("change", "変更影響"),
                            ("test", "テスト管理"),
                            ("general", "一般PMO相談"),
                        ],
                        default="general",
                        max_length=32,
                        verbose_name="意図",
                    ),
                ),
                (
                    "intent_confidence",
                    models.FloatField(default=0.0, verbose_name="意図分類の確信度"),
                ),
                (
                    "plan",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="使用ツール、検索クエリ、期待する出力。仕様書 REQ-AG-003。",
                        verbose_name="実行計画",
                    ),
                ),
                (
                    "loop_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="NFR-AG-002: settings.AGENT['MAX_LOOPS'] を超えないこと。",
                        verbose_name="ループ回数",
                    ),
                ),
                (
                    "elapsed_ms",
                    models.PositiveIntegerField(default=0, verbose_name="所要時間(ms)"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="エラー")),
            ],
            options={
                "verbose_name": "Agentic実行",
                "verbose_name_plural": "Agentic実行",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("order", models.PositiveSmallIntegerField(verbose_name="順序")),
                ("tool_name", models.CharField(max_length=64, verbose_name="ツール名")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "成功"),
                            ("skipped", "スキップ"),
                            ("failed", "失敗"),
                        ],
                        default="ok",
                        max_length=16,
                        verbose_name="状態",
                    ),
                ),
                (
                    "input_summary",
                    models.TextField(blank=True, verbose_name="入力概要"),
                ),
                (
                    "output_summary",
                    models.TextField(blank=True, verbose_name="出力概要"),
                ),
                (
                    "elapsed_ms",
                    models.PositiveIntegerField(default=0, verbose_name="所要時間(ms)"),
                ),
            ],
            options={
                "verbose_name": "実行ステップ",
                "verbose_name_plural": "実行ステップ",
                "ordering": ["run", "order"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceEvaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("confidence", models.FloatField(default=0.0, verbose_name="確信度")),
                (
                    "relevance",
                    models.CharField(
                        choices=[("low", "低"), ("medium", "中"), ("high", "高")],
                        default="low",
                        max_length=16,
                        verbose_name="関連度",
                    ),
                ),
                (
                    "coverage",
                    models.CharField(
                        choices=[("low", "低"), ("medium", "中"), ("high", "高")],
                        default="low",
                        max_length=16,
                        verbose_name="網羅度",
                    ),
                ),
                (
                    "has_conflict",
                    models.BooleanField(default=False, verbose_name="根拠間の矛盾"),
                ),
                (
                    "missing_information",
                    models.JSONField(blank=True, default=list, verbose_name="不足情報"),
                ),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("answer", "回答する"),
                            ("answer_with_caution", "注意付きで回答する"),
                            ("ask_clarification", "追加確認を求める"),
                        ],
                        default="ask_clarification",
                        max_length=32,
                        verbose_name="推奨",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
            ],
            options={
                "verbose_name": "根拠評価",
                "verbose_name_plural": "根拠評価",
            },
        ),
        migrations.CreateModel(
            name="HumanReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "未確認"),
                            ("accepted", "採用"),
                            ("modified", "修正して採用"),
                            ("rejected", "不採用"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="判断",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="コメント")),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="確認日時"
                    ),
                ),
            ],
            options={
                "verbose_name": "人による確認",
                "verbose_name_plural": "人による確認",
                "ordering": ["-created_at"],
            },
        ),
    ]
