# Generated by Django 5.1.15 on 2026-07-30 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("agents", "0001_initial"),
        ("projects", "0001_initial"),
        ("rag", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrun",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_runs",
                to="rag.raganswer",
                verbose_name="生成回答",
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_runs",
                to="projects.project",
                verbose_name="案件",
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_runs",
                to="accounts.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_runs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="実行者",
            ),
        ),
        migrations.AddField(
            model_name="agentstep",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="agents.agentrun",
                verbose_name="実行",
            ),
        ),
        migrations.AddField(
            model_name="evidenceevaluation",
            name="run",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence",
                to="agents.agentrun",
                verbose_name="実行",
            ),
        ),
        migrations.AddField(
            model_name="humanreview",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="確認者",
            ),
        ),
        migrations.AddField(
            model_name="humanreview",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="agents.agentrun",
                verbose_name="実行",
            ),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["tenant", "area", "status"],
                name="agents_agen_tenant__ecbc9c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentstep",
            constraint=models.UniqueConstraint(
                fields=("run", "order"), name="uniq_step_order_per_run"
            ),
        ),
    ]
