# Generated by Django 5.1.15 on 2026-08-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentrun",
            name="area",
            field=models.CharField(
                choices=[
                    ("rag_search", "RAG検索"),
                    ("rag_chat", "RAGチャット"),
                    ("pmo_consultation", "PMO相談"),
                    ("planning", "計画ドラフト"),
                    ("deliverable", "成果物生成"),
                ],
                max_length=32,
                verbose_name="実行画面",
            ),
        ),
    ]
