# Generated by Django 5.1.15 on 2026-07-30 09:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("action", models.CharField(max_length=120, verbose_name="操作")),
                (
                    "target",
                    models.CharField(blank=True, max_length=300, verbose_name="対象"),
                ),
                ("succeeded", models.BooleanField(default=True, verbose_name="成否")),
                ("detail", models.TextField(blank=True, verbose_name="詳細")),
            ],
            options={
                "verbose_name": "操作ログ",
                "verbose_name_plural": "操作ログ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "rating",
                    models.SmallIntegerField(
                        choices=[
                            (1, "役に立たなかった"),
                            (2, "どちらとも言えない"),
                            (3, "役に立った"),
                        ],
                        verbose_name="評価",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="コメント")),
                (
                    "has_fact_error",
                    models.BooleanField(
                        default=False,
                        help_text="PoC の受け入れ条件「事実誤認 0 件」の集計に使う。",
                        verbose_name="事実誤認あり",
                    ),
                ),
                (
                    "agent_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="agents.agentrun",
                        verbose_name="対象実行",
                    ),
                ),
            ],
            options={
                "verbose_name": "フィードバック",
                "verbose_name_plural": "フィードバック",
                "ordering": ["-created_at"],
            },
        ),
    ]
