# Generated by Django 5.1.15 on 2026-07-30 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("audit", "0001_initial"),
        ("projects", "0001_initial"),
        ("rag", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="rag.raganswer",
                verbose_name="対象回答",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="accounts.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedbacks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="投稿者",
            ),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operation_logs",
                to="projects.project",
                verbose_name="案件",
            ),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operation_logs",
                to="accounts.tenant",
                verbose_name="テナント",
            ),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operation_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="実施者",
            ),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(
                fields=["tenant", "action", "created_at"],
                name="audit_opera_tenant__c9b260_idx",
            ),
        ),
    ]
